// pcie_hip_avmm_mm_interconnect_3.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.0 211

`timescale 1 ps / 1 ps
module pcie_hip_avmm_mm_interconnect_3 (
		input  wire         DUT_coreclkout_clk,                                                  //                                                DUT_coreclkout.clk
		input  wire         mem_if_ddr3_emif_1_afi_clk_clk,                                      //                                    mem_if_ddr3_emif_1_afi_clk.clk
		input  wire         DUT_Rxm_BAR4_translator_reset_reset_bridge_in_reset_reset,           //           DUT_Rxm_BAR4_translator_reset_reset_bridge_in_reset.reset
		input  wire         mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset, // mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset.reset
		input  wire         mem_if_ddr3_emif_1_soft_reset_reset_bridge_in_reset_reset,           //           mem_if_ddr3_emif_1_soft_reset_reset_bridge_in_reset.reset
		input  wire [63:0]  DUT_Rxm_BAR4_address,                                                //                                                  DUT_Rxm_BAR4.address
		output wire         DUT_Rxm_BAR4_waitrequest,                                            //                                                              .waitrequest
		input  wire [5:0]   DUT_Rxm_BAR4_burstcount,                                             //                                                              .burstcount
		input  wire [15:0]  DUT_Rxm_BAR4_byteenable,                                             //                                                              .byteenable
		input  wire         DUT_Rxm_BAR4_read,                                                   //                                                              .read
		output wire [127:0] DUT_Rxm_BAR4_readdata,                                               //                                                              .readdata
		output wire         DUT_Rxm_BAR4_readdatavalid,                                          //                                                              .readdatavalid
		input  wire         DUT_Rxm_BAR4_write,                                                  //                                                              .write
		input  wire [127:0] DUT_Rxm_BAR4_writedata,                                              //                                                              .writedata
		output wire [23:0]  mem_if_ddr3_emif_1_avl_address,                                      //                                        mem_if_ddr3_emif_1_avl.address
		output wire         mem_if_ddr3_emif_1_avl_write,                                        //                                                              .write
		output wire         mem_if_ddr3_emif_1_avl_read,                                         //                                                              .read
		input  wire [511:0] mem_if_ddr3_emif_1_avl_readdata,                                     //                                                              .readdata
		output wire [511:0] mem_if_ddr3_emif_1_avl_writedata,                                    //                                                              .writedata
		output wire         mem_if_ddr3_emif_1_avl_beginbursttransfer,                           //                                                              .beginbursttransfer
		output wire [2:0]   mem_if_ddr3_emif_1_avl_burstcount,                                   //                                                              .burstcount
		output wire [63:0]  mem_if_ddr3_emif_1_avl_byteenable,                                   //                                                              .byteenable
		input  wire         mem_if_ddr3_emif_1_avl_readdatavalid,                                //                                                              .readdatavalid
		input  wire         mem_if_ddr3_emif_1_avl_waitrequest                                   //                                                              .waitrequest
	);

	wire          dut_rxm_bar4_translator_avalon_universal_master_0_waitrequest;   // DUT_Rxm_BAR4_agent:av_waitrequest -> DUT_Rxm_BAR4_translator:uav_waitrequest
	wire  [127:0] dut_rxm_bar4_translator_avalon_universal_master_0_readdata;      // DUT_Rxm_BAR4_agent:av_readdata -> DUT_Rxm_BAR4_translator:uav_readdata
	wire          dut_rxm_bar4_translator_avalon_universal_master_0_debugaccess;   // DUT_Rxm_BAR4_translator:uav_debugaccess -> DUT_Rxm_BAR4_agent:av_debugaccess
	wire   [63:0] dut_rxm_bar4_translator_avalon_universal_master_0_address;       // DUT_Rxm_BAR4_translator:uav_address -> DUT_Rxm_BAR4_agent:av_address
	wire          dut_rxm_bar4_translator_avalon_universal_master_0_read;          // DUT_Rxm_BAR4_translator:uav_read -> DUT_Rxm_BAR4_agent:av_read
	wire   [15:0] dut_rxm_bar4_translator_avalon_universal_master_0_byteenable;    // DUT_Rxm_BAR4_translator:uav_byteenable -> DUT_Rxm_BAR4_agent:av_byteenable
	wire          dut_rxm_bar4_translator_avalon_universal_master_0_readdatavalid; // DUT_Rxm_BAR4_agent:av_readdatavalid -> DUT_Rxm_BAR4_translator:uav_readdatavalid
	wire          dut_rxm_bar4_translator_avalon_universal_master_0_lock;          // DUT_Rxm_BAR4_translator:uav_lock -> DUT_Rxm_BAR4_agent:av_lock
	wire          dut_rxm_bar4_translator_avalon_universal_master_0_write;         // DUT_Rxm_BAR4_translator:uav_write -> DUT_Rxm_BAR4_agent:av_write
	wire  [127:0] dut_rxm_bar4_translator_avalon_universal_master_0_writedata;     // DUT_Rxm_BAR4_translator:uav_writedata -> DUT_Rxm_BAR4_agent:av_writedata
	wire    [9:0] dut_rxm_bar4_translator_avalon_universal_master_0_burstcount;    // DUT_Rxm_BAR4_translator:uav_burstcount -> DUT_Rxm_BAR4_agent:av_burstcount
	wire          rsp_mux_src_valid;                                               // rsp_mux:src_valid -> DUT_Rxm_BAR4_agent:rp_valid
	wire  [248:0] rsp_mux_src_data;                                                // rsp_mux:src_data -> DUT_Rxm_BAR4_agent:rp_data
	wire          rsp_mux_src_ready;                                               // DUT_Rxm_BAR4_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                             // rsp_mux:src_channel -> DUT_Rxm_BAR4_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                       // rsp_mux:src_startofpacket -> DUT_Rxm_BAR4_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                         // rsp_mux:src_endofpacket -> DUT_Rxm_BAR4_agent:rp_endofpacket
	wire  [511:0] mem_if_ddr3_emif_1_avl_agent_m0_readdata;                        // mem_if_ddr3_emif_1_avl_translator:uav_readdata -> mem_if_ddr3_emif_1_avl_agent:m0_readdata
	wire          mem_if_ddr3_emif_1_avl_agent_m0_waitrequest;                     // mem_if_ddr3_emif_1_avl_translator:uav_waitrequest -> mem_if_ddr3_emif_1_avl_agent:m0_waitrequest
	wire          mem_if_ddr3_emif_1_avl_agent_m0_debugaccess;                     // mem_if_ddr3_emif_1_avl_agent:m0_debugaccess -> mem_if_ddr3_emif_1_avl_translator:uav_debugaccess
	wire   [63:0] mem_if_ddr3_emif_1_avl_agent_m0_address;                         // mem_if_ddr3_emif_1_avl_agent:m0_address -> mem_if_ddr3_emif_1_avl_translator:uav_address
	wire   [63:0] mem_if_ddr3_emif_1_avl_agent_m0_byteenable;                      // mem_if_ddr3_emif_1_avl_agent:m0_byteenable -> mem_if_ddr3_emif_1_avl_translator:uav_byteenable
	wire          mem_if_ddr3_emif_1_avl_agent_m0_read;                            // mem_if_ddr3_emif_1_avl_agent:m0_read -> mem_if_ddr3_emif_1_avl_translator:uav_read
	wire          mem_if_ddr3_emif_1_avl_agent_m0_readdatavalid;                   // mem_if_ddr3_emif_1_avl_translator:uav_readdatavalid -> mem_if_ddr3_emif_1_avl_agent:m0_readdatavalid
	wire          mem_if_ddr3_emif_1_avl_agent_m0_lock;                            // mem_if_ddr3_emif_1_avl_agent:m0_lock -> mem_if_ddr3_emif_1_avl_translator:uav_lock
	wire  [511:0] mem_if_ddr3_emif_1_avl_agent_m0_writedata;                       // mem_if_ddr3_emif_1_avl_agent:m0_writedata -> mem_if_ddr3_emif_1_avl_translator:uav_writedata
	wire          mem_if_ddr3_emif_1_avl_agent_m0_write;                           // mem_if_ddr3_emif_1_avl_agent:m0_write -> mem_if_ddr3_emif_1_avl_translator:uav_write
	wire    [8:0] mem_if_ddr3_emif_1_avl_agent_m0_burstcount;                      // mem_if_ddr3_emif_1_avl_agent:m0_burstcount -> mem_if_ddr3_emif_1_avl_translator:uav_burstcount
	wire          mem_if_ddr3_emif_1_avl_agent_rf_source_valid;                    // mem_if_ddr3_emif_1_avl_agent:rf_source_valid -> mem_if_ddr3_emif_1_avl_agent_rsp_fifo:in_valid
	wire  [681:0] mem_if_ddr3_emif_1_avl_agent_rf_source_data;                     // mem_if_ddr3_emif_1_avl_agent:rf_source_data -> mem_if_ddr3_emif_1_avl_agent_rsp_fifo:in_data
	wire          mem_if_ddr3_emif_1_avl_agent_rf_source_ready;                    // mem_if_ddr3_emif_1_avl_agent_rsp_fifo:in_ready -> mem_if_ddr3_emif_1_avl_agent:rf_source_ready
	wire          mem_if_ddr3_emif_1_avl_agent_rf_source_startofpacket;            // mem_if_ddr3_emif_1_avl_agent:rf_source_startofpacket -> mem_if_ddr3_emif_1_avl_agent_rsp_fifo:in_startofpacket
	wire          mem_if_ddr3_emif_1_avl_agent_rf_source_endofpacket;              // mem_if_ddr3_emif_1_avl_agent:rf_source_endofpacket -> mem_if_ddr3_emif_1_avl_agent_rsp_fifo:in_endofpacket
	wire          mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_valid;                 // mem_if_ddr3_emif_1_avl_agent_rsp_fifo:out_valid -> mem_if_ddr3_emif_1_avl_agent:rf_sink_valid
	wire  [681:0] mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_data;                  // mem_if_ddr3_emif_1_avl_agent_rsp_fifo:out_data -> mem_if_ddr3_emif_1_avl_agent:rf_sink_data
	wire          mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_ready;                 // mem_if_ddr3_emif_1_avl_agent:rf_sink_ready -> mem_if_ddr3_emif_1_avl_agent_rsp_fifo:out_ready
	wire          mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_startofpacket;         // mem_if_ddr3_emif_1_avl_agent_rsp_fifo:out_startofpacket -> mem_if_ddr3_emif_1_avl_agent:rf_sink_startofpacket
	wire          mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_endofpacket;           // mem_if_ddr3_emif_1_avl_agent_rsp_fifo:out_endofpacket -> mem_if_ddr3_emif_1_avl_agent:rf_sink_endofpacket
	wire          mem_if_ddr3_emif_1_avl_agent_rdata_fifo_src_valid;               // mem_if_ddr3_emif_1_avl_agent:rdata_fifo_src_valid -> mem_if_ddr3_emif_1_avl_agent_rdata_fifo:in_valid
	wire  [513:0] mem_if_ddr3_emif_1_avl_agent_rdata_fifo_src_data;                // mem_if_ddr3_emif_1_avl_agent:rdata_fifo_src_data -> mem_if_ddr3_emif_1_avl_agent_rdata_fifo:in_data
	wire          mem_if_ddr3_emif_1_avl_agent_rdata_fifo_src_ready;               // mem_if_ddr3_emif_1_avl_agent_rdata_fifo:in_ready -> mem_if_ddr3_emif_1_avl_agent:rdata_fifo_src_ready
	wire          dut_rxm_bar4_agent_cp_valid;                                     // DUT_Rxm_BAR4_agent:cp_valid -> router:sink_valid
	wire  [248:0] dut_rxm_bar4_agent_cp_data;                                      // DUT_Rxm_BAR4_agent:cp_data -> router:sink_data
	wire          dut_rxm_bar4_agent_cp_ready;                                     // router:sink_ready -> DUT_Rxm_BAR4_agent:cp_ready
	wire          dut_rxm_bar4_agent_cp_startofpacket;                             // DUT_Rxm_BAR4_agent:cp_startofpacket -> router:sink_startofpacket
	wire          dut_rxm_bar4_agent_cp_endofpacket;                               // DUT_Rxm_BAR4_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                // router:src_valid -> cmd_demux:sink_valid
	wire  [248:0] router_src_data;                                                 // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                              // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                        // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                          // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          mem_if_ddr3_emif_1_avl_agent_rp_valid;                           // mem_if_ddr3_emif_1_avl_agent:rp_valid -> router_001:sink_valid
	wire  [680:0] mem_if_ddr3_emif_1_avl_agent_rp_data;                            // mem_if_ddr3_emif_1_avl_agent:rp_data -> router_001:sink_data
	wire          mem_if_ddr3_emif_1_avl_agent_rp_ready;                           // router_001:sink_ready -> mem_if_ddr3_emif_1_avl_agent:rp_ready
	wire          mem_if_ddr3_emif_1_avl_agent_rp_startofpacket;                   // mem_if_ddr3_emif_1_avl_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          mem_if_ddr3_emif_1_avl_agent_rp_endofpacket;                     // mem_if_ddr3_emif_1_avl_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          mem_if_ddr3_emif_1_avl_burst_adapter_source0_valid;              // mem_if_ddr3_emif_1_avl_burst_adapter:source0_valid -> mem_if_ddr3_emif_1_avl_agent:cp_valid
	wire  [680:0] mem_if_ddr3_emif_1_avl_burst_adapter_source0_data;               // mem_if_ddr3_emif_1_avl_burst_adapter:source0_data -> mem_if_ddr3_emif_1_avl_agent:cp_data
	wire          mem_if_ddr3_emif_1_avl_burst_adapter_source0_ready;              // mem_if_ddr3_emif_1_avl_agent:cp_ready -> mem_if_ddr3_emif_1_avl_burst_adapter:source0_ready
	wire    [0:0] mem_if_ddr3_emif_1_avl_burst_adapter_source0_channel;            // mem_if_ddr3_emif_1_avl_burst_adapter:source0_channel -> mem_if_ddr3_emif_1_avl_agent:cp_channel
	wire          mem_if_ddr3_emif_1_avl_burst_adapter_source0_startofpacket;      // mem_if_ddr3_emif_1_avl_burst_adapter:source0_startofpacket -> mem_if_ddr3_emif_1_avl_agent:cp_startofpacket
	wire          mem_if_ddr3_emif_1_avl_burst_adapter_source0_endofpacket;        // mem_if_ddr3_emif_1_avl_burst_adapter:source0_endofpacket -> mem_if_ddr3_emif_1_avl_agent:cp_endofpacket
	wire          router_001_src_valid;                                            // router_001:src_valid -> mem_if_ddr3_emif_1_avl_rsp_width_adapter:in_valid
	wire  [680:0] router_001_src_data;                                             // router_001:src_data -> mem_if_ddr3_emif_1_avl_rsp_width_adapter:in_data
	wire          router_001_src_ready;                                            // mem_if_ddr3_emif_1_avl_rsp_width_adapter:in_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                          // router_001:src_channel -> mem_if_ddr3_emif_1_avl_rsp_width_adapter:in_channel
	wire          router_001_src_startofpacket;                                    // router_001:src_startofpacket -> mem_if_ddr3_emif_1_avl_rsp_width_adapter:in_startofpacket
	wire          router_001_src_endofpacket;                                      // router_001:src_endofpacket -> mem_if_ddr3_emif_1_avl_rsp_width_adapter:in_endofpacket
	wire          mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_valid;              // mem_if_ddr3_emif_1_avl_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire  [248:0] mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_data;               // mem_if_ddr3_emif_1_avl_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire          mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_ready;              // rsp_demux:sink_ready -> mem_if_ddr3_emif_1_avl_rsp_width_adapter:out_ready
	wire    [0:0] mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_channel;            // mem_if_ddr3_emif_1_avl_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire          mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_startofpacket;      // mem_if_ddr3_emif_1_avl_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire          mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_endofpacket;        // mem_if_ddr3_emif_1_avl_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_mux_src_valid;                                               // cmd_mux:src_valid -> mem_if_ddr3_emif_1_avl_cmd_width_adapter:in_valid
	wire  [248:0] cmd_mux_src_data;                                                // cmd_mux:src_data -> mem_if_ddr3_emif_1_avl_cmd_width_adapter:in_data
	wire          cmd_mux_src_ready;                                               // mem_if_ddr3_emif_1_avl_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                             // cmd_mux:src_channel -> mem_if_ddr3_emif_1_avl_cmd_width_adapter:in_channel
	wire          cmd_mux_src_startofpacket;                                       // cmd_mux:src_startofpacket -> mem_if_ddr3_emif_1_avl_cmd_width_adapter:in_startofpacket
	wire          cmd_mux_src_endofpacket;                                         // cmd_mux:src_endofpacket -> mem_if_ddr3_emif_1_avl_cmd_width_adapter:in_endofpacket
	wire          mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_valid;              // mem_if_ddr3_emif_1_avl_cmd_width_adapter:out_valid -> mem_if_ddr3_emif_1_avl_burst_adapter:sink0_valid
	wire  [680:0] mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_data;               // mem_if_ddr3_emif_1_avl_cmd_width_adapter:out_data -> mem_if_ddr3_emif_1_avl_burst_adapter:sink0_data
	wire          mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_ready;              // mem_if_ddr3_emif_1_avl_burst_adapter:sink0_ready -> mem_if_ddr3_emif_1_avl_cmd_width_adapter:out_ready
	wire    [0:0] mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_channel;            // mem_if_ddr3_emif_1_avl_cmd_width_adapter:out_channel -> mem_if_ddr3_emif_1_avl_burst_adapter:sink0_channel
	wire          mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_startofpacket;      // mem_if_ddr3_emif_1_avl_cmd_width_adapter:out_startofpacket -> mem_if_ddr3_emif_1_avl_burst_adapter:sink0_startofpacket
	wire          mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_endofpacket;        // mem_if_ddr3_emif_1_avl_cmd_width_adapter:out_endofpacket -> mem_if_ddr3_emif_1_avl_burst_adapter:sink0_endofpacket
	wire          cmd_demux_src0_valid;                                            // cmd_demux:src0_valid -> crosser:in_valid
	wire  [248:0] cmd_demux_src0_data;                                             // cmd_demux:src0_data -> crosser:in_data
	wire          cmd_demux_src0_ready;                                            // crosser:in_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                          // cmd_demux:src0_channel -> crosser:in_channel
	wire          cmd_demux_src0_startofpacket;                                    // cmd_demux:src0_startofpacket -> crosser:in_startofpacket
	wire          cmd_demux_src0_endofpacket;                                      // cmd_demux:src0_endofpacket -> crosser:in_endofpacket
	wire          crosser_out_valid;                                               // crosser:out_valid -> cmd_mux:sink0_valid
	wire  [248:0] crosser_out_data;                                                // crosser:out_data -> cmd_mux:sink0_data
	wire          crosser_out_ready;                                               // cmd_mux:sink0_ready -> crosser:out_ready
	wire    [0:0] crosser_out_channel;                                             // crosser:out_channel -> cmd_mux:sink0_channel
	wire          crosser_out_startofpacket;                                       // crosser:out_startofpacket -> cmd_mux:sink0_startofpacket
	wire          crosser_out_endofpacket;                                         // crosser:out_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                            // rsp_demux:src0_valid -> crosser_001:in_valid
	wire  [248:0] rsp_demux_src0_data;                                             // rsp_demux:src0_data -> crosser_001:in_data
	wire          rsp_demux_src0_ready;                                            // crosser_001:in_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                          // rsp_demux:src0_channel -> crosser_001:in_channel
	wire          rsp_demux_src0_startofpacket;                                    // rsp_demux:src0_startofpacket -> crosser_001:in_startofpacket
	wire          rsp_demux_src0_endofpacket;                                      // rsp_demux:src0_endofpacket -> crosser_001:in_endofpacket
	wire          crosser_001_out_valid;                                           // crosser_001:out_valid -> rsp_mux:sink0_valid
	wire  [248:0] crosser_001_out_data;                                            // crosser_001:out_data -> rsp_mux:sink0_data
	wire          crosser_001_out_ready;                                           // rsp_mux:sink0_ready -> crosser_001:out_ready
	wire    [0:0] crosser_001_out_channel;                                         // crosser_001:out_channel -> rsp_mux:sink0_channel
	wire          crosser_001_out_startofpacket;                                   // crosser_001:out_startofpacket -> rsp_mux:sink0_startofpacket
	wire          crosser_001_out_endofpacket;                                     // crosser_001:out_endofpacket -> rsp_mux:sink0_endofpacket
	wire          mem_if_ddr3_emif_1_avl_agent_rdata_fifo_out_valid;               // mem_if_ddr3_emif_1_avl_agent_rdata_fifo:out_valid -> avalon_st_adapter:in_0_valid
	wire  [513:0] mem_if_ddr3_emif_1_avl_agent_rdata_fifo_out_data;                // mem_if_ddr3_emif_1_avl_agent_rdata_fifo:out_data -> avalon_st_adapter:in_0_data
	wire          mem_if_ddr3_emif_1_avl_agent_rdata_fifo_out_ready;               // avalon_st_adapter:in_0_ready -> mem_if_ddr3_emif_1_avl_agent_rdata_fifo:out_ready
	wire          avalon_st_adapter_out_0_valid;                                   // avalon_st_adapter:out_0_valid -> mem_if_ddr3_emif_1_avl_agent:rdata_fifo_sink_valid
	wire  [513:0] avalon_st_adapter_out_0_data;                                    // avalon_st_adapter:out_0_data -> mem_if_ddr3_emif_1_avl_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                   // mem_if_ddr3_emif_1_avl_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                   // avalon_st_adapter:out_0_error -> mem_if_ddr3_emif_1_avl_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (64),
		.AV_DATA_W                   (128),
		.AV_BURSTCOUNT_W             (6),
		.AV_BYTEENABLE_W             (16),
		.UAV_ADDRESS_W               (64),
		.UAV_BURSTCOUNT_W            (10),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (16),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) dut_rxm_bar4_translator (
		.clk                    (DUT_coreclkout_clk),                                              //                       clk.clk
		.reset                  (DUT_Rxm_BAR4_translator_reset_reset_bridge_in_reset_reset),       //                     reset.reset
		.uav_address            (dut_rxm_bar4_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (dut_rxm_bar4_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (dut_rxm_bar4_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (dut_rxm_bar4_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (dut_rxm_bar4_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (dut_rxm_bar4_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (dut_rxm_bar4_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (dut_rxm_bar4_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (dut_rxm_bar4_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (dut_rxm_bar4_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (dut_rxm_bar4_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (DUT_Rxm_BAR4_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (DUT_Rxm_BAR4_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (DUT_Rxm_BAR4_burstcount),                                         //                          .burstcount
		.av_byteenable          (DUT_Rxm_BAR4_byteenable),                                         //                          .byteenable
		.av_read                (DUT_Rxm_BAR4_read),                                               //                          .read
		.av_readdata            (DUT_Rxm_BAR4_readdata),                                           //                          .readdata
		.av_readdatavalid       (DUT_Rxm_BAR4_readdatavalid),                                      //                          .readdatavalid
		.av_write               (DUT_Rxm_BAR4_write),                                              //                          .write
		.av_writedata           (DUT_Rxm_BAR4_writedata),                                          //                          .writedata
		.av_beginbursttransfer  (1'b0),                                                            //               (terminated)
		.av_begintransfer       (1'b0),                                                            //               (terminated)
		.av_chipselect          (1'b0),                                                            //               (terminated)
		.av_lock                (1'b0),                                                            //               (terminated)
		.av_debugaccess         (1'b0),                                                            //               (terminated)
		.uav_clken              (),                                                                //               (terminated)
		.av_clken               (1'b1),                                                            //               (terminated)
		.uav_response           (2'b00),                                                           //               (terminated)
		.av_response            (),                                                                //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                            //               (terminated)
		.av_writeresponsevalid  ()                                                                 //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (24),
		.AV_DATA_W                      (512),
		.UAV_DATA_W                     (512),
		.AV_BURSTCOUNT_W                (3),
		.AV_BYTEENABLE_W                (64),
		.UAV_BYTEENABLE_W               (64),
		.UAV_ADDRESS_W                  (64),
		.UAV_BURSTCOUNT_W               (9),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (64),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) mem_if_ddr3_emif_1_avl_translator (
		.clk                    (mem_if_ddr3_emif_1_afi_clk_clk),                                      //                      clk.clk
		.reset                  (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (mem_if_ddr3_emif_1_avl_agent_m0_address),                             // avalon_universal_slave_0.address
		.uav_burstcount         (mem_if_ddr3_emif_1_avl_agent_m0_burstcount),                          //                         .burstcount
		.uav_read               (mem_if_ddr3_emif_1_avl_agent_m0_read),                                //                         .read
		.uav_write              (mem_if_ddr3_emif_1_avl_agent_m0_write),                               //                         .write
		.uav_waitrequest        (mem_if_ddr3_emif_1_avl_agent_m0_waitrequest),                         //                         .waitrequest
		.uav_readdatavalid      (mem_if_ddr3_emif_1_avl_agent_m0_readdatavalid),                       //                         .readdatavalid
		.uav_byteenable         (mem_if_ddr3_emif_1_avl_agent_m0_byteenable),                          //                         .byteenable
		.uav_readdata           (mem_if_ddr3_emif_1_avl_agent_m0_readdata),                            //                         .readdata
		.uav_writedata          (mem_if_ddr3_emif_1_avl_agent_m0_writedata),                           //                         .writedata
		.uav_lock               (mem_if_ddr3_emif_1_avl_agent_m0_lock),                                //                         .lock
		.uav_debugaccess        (mem_if_ddr3_emif_1_avl_agent_m0_debugaccess),                         //                         .debugaccess
		.av_address             (mem_if_ddr3_emif_1_avl_address),                                      //      avalon_anti_slave_0.address
		.av_write               (mem_if_ddr3_emif_1_avl_write),                                        //                         .write
		.av_read                (mem_if_ddr3_emif_1_avl_read),                                         //                         .read
		.av_readdata            (mem_if_ddr3_emif_1_avl_readdata),                                     //                         .readdata
		.av_writedata           (mem_if_ddr3_emif_1_avl_writedata),                                    //                         .writedata
		.av_beginbursttransfer  (mem_if_ddr3_emif_1_avl_beginbursttransfer),                           //                         .beginbursttransfer
		.av_burstcount          (mem_if_ddr3_emif_1_avl_burstcount),                                   //                         .burstcount
		.av_byteenable          (mem_if_ddr3_emif_1_avl_byteenable),                                   //                         .byteenable
		.av_readdatavalid       (mem_if_ddr3_emif_1_avl_readdatavalid),                                //                         .readdatavalid
		.av_waitrequest         (mem_if_ddr3_emif_1_avl_waitrequest),                                  //                         .waitrequest
		.av_begintransfer       (),                                                                    //              (terminated)
		.av_writebyteenable     (),                                                                    //              (terminated)
		.av_lock                (),                                                                    //              (terminated)
		.av_chipselect          (),                                                                    //              (terminated)
		.av_clken               (),                                                                    //              (terminated)
		.uav_clken              (1'b0),                                                                //              (terminated)
		.av_debugaccess         (),                                                                    //              (terminated)
		.av_outputenable        (),                                                                    //              (terminated)
		.uav_response           (),                                                                    //              (terminated)
		.av_response            (2'b00),                                                               //              (terminated)
		.uav_writeresponsevalid (),                                                                    //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                 //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (248),
		.PKT_ORI_BURST_SIZE_L      (246),
		.PKT_RESPONSE_STATUS_H     (245),
		.PKT_RESPONSE_STATUS_L     (244),
		.PKT_QOS_H                 (233),
		.PKT_QOS_L                 (233),
		.PKT_DATA_SIDEBAND_H       (231),
		.PKT_DATA_SIDEBAND_L       (231),
		.PKT_ADDR_SIDEBAND_H       (230),
		.PKT_ADDR_SIDEBAND_L       (230),
		.PKT_BURST_TYPE_H          (229),
		.PKT_BURST_TYPE_L          (228),
		.PKT_CACHE_H               (243),
		.PKT_CACHE_L               (240),
		.PKT_THREAD_ID_H           (236),
		.PKT_THREAD_ID_L           (236),
		.PKT_BURST_SIZE_H          (227),
		.PKT_BURST_SIZE_L          (225),
		.PKT_TRANS_EXCLUSIVE       (213),
		.PKT_TRANS_LOCK            (212),
		.PKT_BEGIN_BURST           (232),
		.PKT_PROTECTION_H          (239),
		.PKT_PROTECTION_L          (237),
		.PKT_BURSTWRAP_H           (224),
		.PKT_BURSTWRAP_L           (224),
		.PKT_BYTE_CNT_H            (223),
		.PKT_BYTE_CNT_L            (214),
		.PKT_ADDR_H                (207),
		.PKT_ADDR_L                (144),
		.PKT_TRANS_COMPRESSED_READ (208),
		.PKT_TRANS_POSTED          (209),
		.PKT_TRANS_WRITE           (210),
		.PKT_TRANS_READ            (211),
		.PKT_DATA_H                (127),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_SRC_ID_H              (234),
		.PKT_SRC_ID_L              (234),
		.PKT_DEST_ID_H             (235),
		.PKT_DEST_ID_L             (235),
		.ST_DATA_W                 (249),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (10),
		.SUPPRESS_0_BYTEEN_RSP     (1),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) dut_rxm_bar4_agent (
		.clk                   (DUT_coreclkout_clk),                                              //       clk.clk
		.reset                 (DUT_Rxm_BAR4_translator_reset_reset_bridge_in_reset_reset),       // clk_reset.reset
		.av_address            (dut_rxm_bar4_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (dut_rxm_bar4_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (dut_rxm_bar4_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (dut_rxm_bar4_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (dut_rxm_bar4_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (dut_rxm_bar4_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (dut_rxm_bar4_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (dut_rxm_bar4_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (dut_rxm_bar4_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (dut_rxm_bar4_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (dut_rxm_bar4_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (dut_rxm_bar4_agent_cp_valid),                                     //        cp.valid
		.cp_data               (dut_rxm_bar4_agent_cp_data),                                      //          .data
		.cp_startofpacket      (dut_rxm_bar4_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (dut_rxm_bar4_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (dut_rxm_bar4_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                               //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                //          .data
		.rp_channel            (rsp_mux_src_channel),                                             //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                       //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                         //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                               //          .ready
		.av_response           (),                                                                // (terminated)
		.av_writeresponsevalid ()                                                                 // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (680),
		.PKT_ORI_BURST_SIZE_L      (678),
		.PKT_RESPONSE_STATUS_H     (677),
		.PKT_RESPONSE_STATUS_L     (676),
		.PKT_BURST_SIZE_H          (659),
		.PKT_BURST_SIZE_L          (657),
		.PKT_TRANS_LOCK            (644),
		.PKT_BEGIN_BURST           (664),
		.PKT_PROTECTION_H          (671),
		.PKT_PROTECTION_L          (669),
		.PKT_BURSTWRAP_H           (656),
		.PKT_BURSTWRAP_L           (656),
		.PKT_BYTE_CNT_H            (655),
		.PKT_BYTE_CNT_L            (646),
		.PKT_ADDR_H                (639),
		.PKT_ADDR_L                (576),
		.PKT_TRANS_COMPRESSED_READ (640),
		.PKT_TRANS_POSTED          (641),
		.PKT_TRANS_WRITE           (642),
		.PKT_TRANS_READ            (643),
		.PKT_DATA_H                (511),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (575),
		.PKT_BYTEEN_L              (512),
		.PKT_SRC_ID_H              (666),
		.PKT_SRC_ID_L              (666),
		.PKT_DEST_ID_H             (667),
		.PKT_DEST_ID_L             (667),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (681),
		.AVS_BURSTCOUNT_W          (9),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) mem_if_ddr3_emif_1_avl_agent (
		.clk                     (mem_if_ddr3_emif_1_afi_clk_clk),                                      //             clk.clk
		.reset                   (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (mem_if_ddr3_emif_1_avl_agent_m0_address),                             //              m0.address
		.m0_burstcount           (mem_if_ddr3_emif_1_avl_agent_m0_burstcount),                          //                .burstcount
		.m0_byteenable           (mem_if_ddr3_emif_1_avl_agent_m0_byteenable),                          //                .byteenable
		.m0_debugaccess          (mem_if_ddr3_emif_1_avl_agent_m0_debugaccess),                         //                .debugaccess
		.m0_lock                 (mem_if_ddr3_emif_1_avl_agent_m0_lock),                                //                .lock
		.m0_readdata             (mem_if_ddr3_emif_1_avl_agent_m0_readdata),                            //                .readdata
		.m0_readdatavalid        (mem_if_ddr3_emif_1_avl_agent_m0_readdatavalid),                       //                .readdatavalid
		.m0_read                 (mem_if_ddr3_emif_1_avl_agent_m0_read),                                //                .read
		.m0_waitrequest          (mem_if_ddr3_emif_1_avl_agent_m0_waitrequest),                         //                .waitrequest
		.m0_writedata            (mem_if_ddr3_emif_1_avl_agent_m0_writedata),                           //                .writedata
		.m0_write                (mem_if_ddr3_emif_1_avl_agent_m0_write),                               //                .write
		.rp_endofpacket          (mem_if_ddr3_emif_1_avl_agent_rp_endofpacket),                         //              rp.endofpacket
		.rp_ready                (mem_if_ddr3_emif_1_avl_agent_rp_ready),                               //                .ready
		.rp_valid                (mem_if_ddr3_emif_1_avl_agent_rp_valid),                               //                .valid
		.rp_data                 (mem_if_ddr3_emif_1_avl_agent_rp_data),                                //                .data
		.rp_startofpacket        (mem_if_ddr3_emif_1_avl_agent_rp_startofpacket),                       //                .startofpacket
		.cp_ready                (mem_if_ddr3_emif_1_avl_burst_adapter_source0_ready),                  //              cp.ready
		.cp_valid                (mem_if_ddr3_emif_1_avl_burst_adapter_source0_valid),                  //                .valid
		.cp_data                 (mem_if_ddr3_emif_1_avl_burst_adapter_source0_data),                   //                .data
		.cp_startofpacket        (mem_if_ddr3_emif_1_avl_burst_adapter_source0_startofpacket),          //                .startofpacket
		.cp_endofpacket          (mem_if_ddr3_emif_1_avl_burst_adapter_source0_endofpacket),            //                .endofpacket
		.cp_channel              (mem_if_ddr3_emif_1_avl_burst_adapter_source0_channel),                //                .channel
		.rf_sink_ready           (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_ready),                     //         rf_sink.ready
		.rf_sink_valid           (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_valid),                     //                .valid
		.rf_sink_startofpacket   (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_startofpacket),             //                .startofpacket
		.rf_sink_endofpacket     (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_endofpacket),               //                .endofpacket
		.rf_sink_data            (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_data),                      //                .data
		.rf_source_ready         (mem_if_ddr3_emif_1_avl_agent_rf_source_ready),                        //       rf_source.ready
		.rf_source_valid         (mem_if_ddr3_emif_1_avl_agent_rf_source_valid),                        //                .valid
		.rf_source_startofpacket (mem_if_ddr3_emif_1_avl_agent_rf_source_startofpacket),                //                .startofpacket
		.rf_source_endofpacket   (mem_if_ddr3_emif_1_avl_agent_rf_source_endofpacket),                  //                .endofpacket
		.rf_source_data          (mem_if_ddr3_emif_1_avl_agent_rf_source_data),                         //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                                       // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                                       //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                                        //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                                       //                .error
		.rdata_fifo_src_ready    (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_src_ready),                   //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_src_valid),                   //                .valid
		.rdata_fifo_src_data     (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_src_data),                    //                .data
		.m0_response             (2'b00),                                                               //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                 //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (682),
		.FIFO_DEPTH          (33),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) mem_if_ddr3_emif_1_avl_agent_rsp_fifo (
		.clk               (mem_if_ddr3_emif_1_afi_clk_clk),                                      //       clk.clk
		.reset             (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (mem_if_ddr3_emif_1_avl_agent_rf_source_data),                         //        in.data
		.in_valid          (mem_if_ddr3_emif_1_avl_agent_rf_source_valid),                        //          .valid
		.in_ready          (mem_if_ddr3_emif_1_avl_agent_rf_source_ready),                        //          .ready
		.in_startofpacket  (mem_if_ddr3_emif_1_avl_agent_rf_source_startofpacket),                //          .startofpacket
		.in_endofpacket    (mem_if_ddr3_emif_1_avl_agent_rf_source_endofpacket),                  //          .endofpacket
		.out_data          (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_data),                      //       out.data
		.out_valid         (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_valid),                     //          .valid
		.out_ready         (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_ready),                     //          .ready
		.out_startofpacket (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_startofpacket),             //          .startofpacket
		.out_endofpacket   (mem_if_ddr3_emif_1_avl_agent_rsp_fifo_out_endofpacket),               //          .endofpacket
		.csr_address       (2'b00),                                                               // (terminated)
		.csr_read          (1'b0),                                                                // (terminated)
		.csr_write         (1'b0),                                                                // (terminated)
		.csr_readdata      (),                                                                    // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                // (terminated)
		.almost_full_data  (),                                                                    // (terminated)
		.almost_empty_data (),                                                                    // (terminated)
		.in_empty          (1'b0),                                                                // (terminated)
		.out_empty         (),                                                                    // (terminated)
		.in_error          (1'b0),                                                                // (terminated)
		.out_error         (),                                                                    // (terminated)
		.in_channel        (1'b0),                                                                // (terminated)
		.out_channel       ()                                                                     // (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (514),
		.FIFO_DEPTH          (256),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (3),
		.USE_MEMORY_BLOCKS   (1),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) mem_if_ddr3_emif_1_avl_agent_rdata_fifo (
		.clk               (mem_if_ddr3_emif_1_afi_clk_clk),                                      //       clk.clk
		.reset             (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_src_data),                    //        in.data
		.in_valid          (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_src_valid),                   //          .valid
		.in_ready          (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_src_ready),                   //          .ready
		.out_data          (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_out_data),                    //       out.data
		.out_valid         (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_out_valid),                   //          .valid
		.out_ready         (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_out_ready),                   //          .ready
		.csr_address       (2'b00),                                                               // (terminated)
		.csr_read          (1'b0),                                                                // (terminated)
		.csr_write         (1'b0),                                                                // (terminated)
		.csr_readdata      (),                                                                    // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                // (terminated)
		.almost_full_data  (),                                                                    // (terminated)
		.almost_empty_data (),                                                                    // (terminated)
		.in_startofpacket  (1'b0),                                                                // (terminated)
		.in_endofpacket    (1'b0),                                                                // (terminated)
		.out_startofpacket (),                                                                    // (terminated)
		.out_endofpacket   (),                                                                    // (terminated)
		.in_empty          (1'b0),                                                                // (terminated)
		.out_empty         (),                                                                    // (terminated)
		.in_error          (1'b0),                                                                // (terminated)
		.out_error         (),                                                                    // (terminated)
		.in_channel        (1'b0),                                                                // (terminated)
		.out_channel       ()                                                                     // (terminated)
	);

	pcie_hip_avmm_mm_interconnect_2_router router (
		.sink_ready         (dut_rxm_bar4_agent_cp_ready),                               //      sink.ready
		.sink_valid         (dut_rxm_bar4_agent_cp_valid),                               //          .valid
		.sink_data          (dut_rxm_bar4_agent_cp_data),                                //          .data
		.sink_startofpacket (dut_rxm_bar4_agent_cp_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (dut_rxm_bar4_agent_cp_endofpacket),                         //          .endofpacket
		.clk                (DUT_coreclkout_clk),                                        //       clk.clk
		.reset              (DUT_Rxm_BAR4_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                          //       src.ready
		.src_valid          (router_src_valid),                                          //          .valid
		.src_data           (router_src_data),                                           //          .data
		.src_channel        (router_src_channel),                                        //          .channel
		.src_startofpacket  (router_src_startofpacket),                                  //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                     //          .endofpacket
	);

	pcie_hip_avmm_mm_interconnect_2_router_001 router_001 (
		.sink_ready         (mem_if_ddr3_emif_1_avl_agent_rp_ready),                               //      sink.ready
		.sink_valid         (mem_if_ddr3_emif_1_avl_agent_rp_valid),                               //          .valid
		.sink_data          (mem_if_ddr3_emif_1_avl_agent_rp_data),                                //          .data
		.sink_startofpacket (mem_if_ddr3_emif_1_avl_agent_rp_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (mem_if_ddr3_emif_1_avl_agent_rp_endofpacket),                         //          .endofpacket
		.clk                (mem_if_ddr3_emif_1_afi_clk_clk),                                      //       clk.clk
		.reset              (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                                //       src.ready
		.src_valid          (router_001_src_valid),                                                //          .valid
		.src_data           (router_001_src_data),                                                 //          .data
		.src_channel        (router_001_src_channel),                                              //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                        //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                           //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (639),
		.PKT_ADDR_L                (576),
		.PKT_BEGIN_BURST           (664),
		.PKT_BYTE_CNT_H            (655),
		.PKT_BYTE_CNT_L            (646),
		.PKT_BYTEEN_H              (575),
		.PKT_BYTEEN_L              (512),
		.PKT_BURST_SIZE_H          (659),
		.PKT_BURST_SIZE_L          (657),
		.PKT_BURST_TYPE_H          (661),
		.PKT_BURST_TYPE_L          (660),
		.PKT_BURSTWRAP_H           (656),
		.PKT_BURSTWRAP_L           (656),
		.PKT_TRANS_COMPRESSED_READ (640),
		.PKT_TRANS_WRITE           (642),
		.PKT_TRANS_READ            (643),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (681),
		.ST_CHANNEL_W              (1),
		.OUT_BYTE_CNT_H            (654),
		.OUT_BURSTWRAP_H           (656),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("13.1")
	) mem_if_ddr3_emif_1_avl_burst_adapter (
		.clk                   (mem_if_ddr3_emif_1_afi_clk_clk),                                      //       cr0.clk
		.reset                 (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.sink0_valid           (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_valid),                  //     sink0.valid
		.sink0_data            (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_data),                   //          .data
		.sink0_channel         (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_channel),                //          .channel
		.sink0_startofpacket   (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_startofpacket),          //          .startofpacket
		.sink0_endofpacket     (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_endofpacket),            //          .endofpacket
		.sink0_ready           (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_ready),                  //          .ready
		.source0_valid         (mem_if_ddr3_emif_1_avl_burst_adapter_source0_valid),                  //   source0.valid
		.source0_data          (mem_if_ddr3_emif_1_avl_burst_adapter_source0_data),                   //          .data
		.source0_channel       (mem_if_ddr3_emif_1_avl_burst_adapter_source0_channel),                //          .channel
		.source0_startofpacket (mem_if_ddr3_emif_1_avl_burst_adapter_source0_startofpacket),          //          .startofpacket
		.source0_endofpacket   (mem_if_ddr3_emif_1_avl_burst_adapter_source0_endofpacket),            //          .endofpacket
		.source0_ready         (mem_if_ddr3_emif_1_avl_burst_adapter_source0_ready)                   //          .ready
	);

	pcie_hip_avmm_mm_interconnect_1_cmd_demux cmd_demux (
		.clk                (DUT_coreclkout_clk),                                        //       clk.clk
		.reset              (DUT_Rxm_BAR4_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                          //      sink.ready
		.sink_channel       (router_src_channel),                                        //          .channel
		.sink_data          (router_src_data),                                           //          .data
		.sink_startofpacket (router_src_startofpacket),                                  //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                    //          .endofpacket
		.sink_valid         (router_src_valid),                                          //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                      //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                      //          .valid
		.src0_data          (cmd_demux_src0_data),                                       //          .data
		.src0_channel       (cmd_demux_src0_channel),                                    //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                              //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                 //          .endofpacket
	);

	pcie_hip_avmm_mm_interconnect_1_cmd_mux cmd_mux (
		.clk                 (mem_if_ddr3_emif_1_afi_clk_clk),                                      //       clk.clk
		.reset               (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                                   //       src.ready
		.src_valid           (cmd_mux_src_valid),                                                   //          .valid
		.src_data            (cmd_mux_src_data),                                                    //          .data
		.src_channel         (cmd_mux_src_channel),                                                 //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                           //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                             //          .endofpacket
		.sink0_ready         (crosser_out_ready),                                                   //     sink0.ready
		.sink0_valid         (crosser_out_valid),                                                   //          .valid
		.sink0_channel       (crosser_out_channel),                                                 //          .channel
		.sink0_data          (crosser_out_data),                                                    //          .data
		.sink0_startofpacket (crosser_out_startofpacket),                                           //          .startofpacket
		.sink0_endofpacket   (crosser_out_endofpacket)                                              //          .endofpacket
	);

	pcie_hip_avmm_mm_interconnect_2_rsp_demux rsp_demux (
		.clk                (mem_if_ddr3_emif_1_afi_clk_clk),                                      //       clk.clk
		.reset              (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_ready),                  //      sink.ready
		.sink_channel       (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_channel),                //          .channel
		.sink_data          (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_data),                   //          .data
		.sink_startofpacket (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_startofpacket),          //          .startofpacket
		.sink_endofpacket   (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_endofpacket),            //          .endofpacket
		.sink_valid         (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_valid),                  //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                                //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                                //          .valid
		.src0_data          (rsp_demux_src0_data),                                                 //          .data
		.src0_channel       (rsp_demux_src0_channel),                                              //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                                        //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                                           //          .endofpacket
	);

	pcie_hip_avmm_mm_interconnect_1_rsp_mux rsp_mux (
		.clk                 (DUT_coreclkout_clk),                                        //       clk.clk
		.reset               (DUT_Rxm_BAR4_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                         //       src.ready
		.src_valid           (rsp_mux_src_valid),                                         //          .valid
		.src_data            (rsp_mux_src_data),                                          //          .data
		.src_channel         (rsp_mux_src_channel),                                       //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                 //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                   //          .endofpacket
		.sink0_ready         (crosser_001_out_ready),                                     //     sink0.ready
		.sink0_valid         (crosser_001_out_valid),                                     //          .valid
		.sink0_channel       (crosser_001_out_channel),                                   //          .channel
		.sink0_data          (crosser_001_out_data),                                      //          .data
		.sink0_startofpacket (crosser_001_out_startofpacket),                             //          .startofpacket
		.sink0_endofpacket   (crosser_001_out_endofpacket)                                //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (639),
		.IN_PKT_ADDR_L                 (576),
		.IN_PKT_DATA_H                 (511),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (575),
		.IN_PKT_BYTEEN_L               (512),
		.IN_PKT_BYTE_CNT_H             (655),
		.IN_PKT_BYTE_CNT_L             (646),
		.IN_PKT_TRANS_COMPRESSED_READ  (640),
		.IN_PKT_TRANS_WRITE            (642),
		.IN_PKT_BURSTWRAP_H            (656),
		.IN_PKT_BURSTWRAP_L            (656),
		.IN_PKT_BURST_SIZE_H           (659),
		.IN_PKT_BURST_SIZE_L           (657),
		.IN_PKT_RESPONSE_STATUS_H      (677),
		.IN_PKT_RESPONSE_STATUS_L      (676),
		.IN_PKT_TRANS_EXCLUSIVE        (645),
		.IN_PKT_BURST_TYPE_H           (661),
		.IN_PKT_BURST_TYPE_L           (660),
		.IN_PKT_ORI_BURST_SIZE_L       (678),
		.IN_PKT_ORI_BURST_SIZE_H       (680),
		.IN_ST_DATA_W                  (681),
		.OUT_PKT_ADDR_H                (207),
		.OUT_PKT_ADDR_L                (144),
		.OUT_PKT_DATA_H                (127),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (143),
		.OUT_PKT_BYTEEN_L              (128),
		.OUT_PKT_BYTE_CNT_H            (223),
		.OUT_PKT_BYTE_CNT_L            (214),
		.OUT_PKT_TRANS_COMPRESSED_READ (208),
		.OUT_PKT_BURST_SIZE_H          (227),
		.OUT_PKT_BURST_SIZE_L          (225),
		.OUT_PKT_RESPONSE_STATUS_H     (245),
		.OUT_PKT_RESPONSE_STATUS_L     (244),
		.OUT_PKT_TRANS_EXCLUSIVE       (213),
		.OUT_PKT_BURST_TYPE_H          (229),
		.OUT_PKT_BURST_TYPE_L          (228),
		.OUT_PKT_ORI_BURST_SIZE_L      (246),
		.OUT_PKT_ORI_BURST_SIZE_H      (248),
		.OUT_ST_DATA_W                 (249),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) mem_if_ddr3_emif_1_avl_rsp_width_adapter (
		.clk                  (mem_if_ddr3_emif_1_afi_clk_clk),                                      //       clk.clk
		.reset                (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (router_001_src_valid),                                                //      sink.valid
		.in_channel           (router_001_src_channel),                                              //          .channel
		.in_startofpacket     (router_001_src_startofpacket),                                        //          .startofpacket
		.in_endofpacket       (router_001_src_endofpacket),                                          //          .endofpacket
		.in_ready             (router_001_src_ready),                                                //          .ready
		.in_data              (router_001_src_data),                                                 //          .data
		.out_endofpacket      (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_endofpacket),            //       src.endofpacket
		.out_data             (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_data),                   //          .data
		.out_channel          (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_channel),                //          .channel
		.out_valid            (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_valid),                  //          .valid
		.out_ready            (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_ready),                  //          .ready
		.out_startofpacket    (mem_if_ddr3_emif_1_avl_rsp_width_adapter_src_startofpacket),          //          .startofpacket
		.in_command_size_data (3'b000)                                                               // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (207),
		.IN_PKT_ADDR_L                 (144),
		.IN_PKT_DATA_H                 (127),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (143),
		.IN_PKT_BYTEEN_L               (128),
		.IN_PKT_BYTE_CNT_H             (223),
		.IN_PKT_BYTE_CNT_L             (214),
		.IN_PKT_TRANS_COMPRESSED_READ  (208),
		.IN_PKT_TRANS_WRITE            (210),
		.IN_PKT_BURSTWRAP_H            (224),
		.IN_PKT_BURSTWRAP_L            (224),
		.IN_PKT_BURST_SIZE_H           (227),
		.IN_PKT_BURST_SIZE_L           (225),
		.IN_PKT_RESPONSE_STATUS_H      (245),
		.IN_PKT_RESPONSE_STATUS_L      (244),
		.IN_PKT_TRANS_EXCLUSIVE        (213),
		.IN_PKT_BURST_TYPE_H           (229),
		.IN_PKT_BURST_TYPE_L           (228),
		.IN_PKT_ORI_BURST_SIZE_L       (246),
		.IN_PKT_ORI_BURST_SIZE_H       (248),
		.IN_ST_DATA_W                  (249),
		.OUT_PKT_ADDR_H                (639),
		.OUT_PKT_ADDR_L                (576),
		.OUT_PKT_DATA_H                (511),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (575),
		.OUT_PKT_BYTEEN_L              (512),
		.OUT_PKT_BYTE_CNT_H            (655),
		.OUT_PKT_BYTE_CNT_L            (646),
		.OUT_PKT_TRANS_COMPRESSED_READ (640),
		.OUT_PKT_BURST_SIZE_H          (659),
		.OUT_PKT_BURST_SIZE_L          (657),
		.OUT_PKT_RESPONSE_STATUS_H     (677),
		.OUT_PKT_RESPONSE_STATUS_L     (676),
		.OUT_PKT_TRANS_EXCLUSIVE       (645),
		.OUT_PKT_BURST_TYPE_H          (661),
		.OUT_PKT_BURST_TYPE_L          (660),
		.OUT_PKT_ORI_BURST_SIZE_L      (678),
		.OUT_PKT_ORI_BURST_SIZE_H      (680),
		.OUT_ST_DATA_W                 (681),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) mem_if_ddr3_emif_1_avl_cmd_width_adapter (
		.clk                  (mem_if_ddr3_emif_1_afi_clk_clk),                                      //       clk.clk
		.reset                (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                                                   //      sink.valid
		.in_channel           (cmd_mux_src_channel),                                                 //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                                           //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                                             //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                                                   //          .ready
		.in_data              (cmd_mux_src_data),                                                    //          .data
		.out_endofpacket      (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_endofpacket),            //       src.endofpacket
		.out_data             (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_data),                   //          .data
		.out_channel          (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_channel),                //          .channel
		.out_valid            (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_valid),                  //          .valid
		.out_ready            (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_ready),                  //          .ready
		.out_startofpacket    (mem_if_ddr3_emif_1_avl_cmd_width_adapter_src_startofpacket),          //          .startofpacket
		.in_command_size_data (3'b000)                                                               // (terminated)
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (249),
		.BITS_PER_SYMBOL     (249),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (1),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser (
		.in_clk            (DUT_coreclkout_clk),                                                  //        in_clk.clk
		.in_reset          (DUT_Rxm_BAR4_translator_reset_reset_bridge_in_reset_reset),           //  in_clk_reset.reset
		.out_clk           (mem_if_ddr3_emif_1_afi_clk_clk),                                      //       out_clk.clk
		.out_reset         (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // out_clk_reset.reset
		.in_ready          (cmd_demux_src0_ready),                                                //            in.ready
		.in_valid          (cmd_demux_src0_valid),                                                //              .valid
		.in_startofpacket  (cmd_demux_src0_startofpacket),                                        //              .startofpacket
		.in_endofpacket    (cmd_demux_src0_endofpacket),                                          //              .endofpacket
		.in_channel        (cmd_demux_src0_channel),                                              //              .channel
		.in_data           (cmd_demux_src0_data),                                                 //              .data
		.out_ready         (crosser_out_ready),                                                   //           out.ready
		.out_valid         (crosser_out_valid),                                                   //              .valid
		.out_startofpacket (crosser_out_startofpacket),                                           //              .startofpacket
		.out_endofpacket   (crosser_out_endofpacket),                                             //              .endofpacket
		.out_channel       (crosser_out_channel),                                                 //              .channel
		.out_data          (crosser_out_data),                                                    //              .data
		.in_empty          (1'b0),                                                                //   (terminated)
		.in_error          (1'b0),                                                                //   (terminated)
		.out_empty         (),                                                                    //   (terminated)
		.out_error         ()                                                                     //   (terminated)
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (249),
		.BITS_PER_SYMBOL     (249),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (1),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser_001 (
		.in_clk            (mem_if_ddr3_emif_1_afi_clk_clk),                                      //        in_clk.clk
		.in_reset          (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), //  in_clk_reset.reset
		.out_clk           (DUT_coreclkout_clk),                                                  //       out_clk.clk
		.out_reset         (DUT_Rxm_BAR4_translator_reset_reset_bridge_in_reset_reset),           // out_clk_reset.reset
		.in_ready          (rsp_demux_src0_ready),                                                //            in.ready
		.in_valid          (rsp_demux_src0_valid),                                                //              .valid
		.in_startofpacket  (rsp_demux_src0_startofpacket),                                        //              .startofpacket
		.in_endofpacket    (rsp_demux_src0_endofpacket),                                          //              .endofpacket
		.in_channel        (rsp_demux_src0_channel),                                              //              .channel
		.in_data           (rsp_demux_src0_data),                                                 //              .data
		.out_ready         (crosser_001_out_ready),                                               //           out.ready
		.out_valid         (crosser_001_out_valid),                                               //              .valid
		.out_startofpacket (crosser_001_out_startofpacket),                                       //              .startofpacket
		.out_endofpacket   (crosser_001_out_endofpacket),                                         //              .endofpacket
		.out_channel       (crosser_001_out_channel),                                             //              .channel
		.out_data          (crosser_001_out_data),                                                //              .data
		.in_empty          (1'b0),                                                                //   (terminated)
		.in_error          (1'b0),                                                                //   (terminated)
		.out_empty         (),                                                                    //   (terminated)
		.out_error         ()                                                                     //   (terminated)
	);

	pcie_hip_avmm_mm_interconnect_2_avalon_st_adapter #(
		.inBitsPerSymbol (514),
		.inUsePackets    (0),
		.inDataWidth     (514),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (514),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (mem_if_ddr3_emif_1_afi_clk_clk),                                      // in_clk_0.clk
		.in_rst_0_reset (mem_if_ddr3_emif_1_avl_translator_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_out_data),                    //     in_0.data
		.in_0_valid     (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_out_valid),                   //         .valid
		.in_0_ready     (mem_if_ddr3_emif_1_avl_agent_rdata_fifo_out_ready),                   //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                                        //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                                       //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                                       //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                                        //         .error
	);

endmodule
