	pcie_hip_avmm u0 (
		.avl_to_asmi_0_conduit_end_sfl_address       (<connected-to-avl_to_asmi_0_conduit_end_sfl_address>),       // avl_to_asmi_0_conduit_end.sfl_address
		.avl_to_asmi_0_conduit_end_sfl_read          (<connected-to-avl_to_asmi_0_conduit_end_sfl_read>),          //                          .sfl_read
		.avl_to_asmi_0_conduit_end_sfl_readdata_from (<connected-to-avl_to_asmi_0_conduit_end_sfl_readdata_from>), //                          .sfl_readdata_from
		.avl_to_asmi_0_conduit_end_sfl_write         (<connected-to-avl_to_asmi_0_conduit_end_sfl_write>),         //                          .sfl_write
		.avl_to_asmi_0_conduit_end_sfl_writedata_to  (<connected-to-avl_to_asmi_0_conduit_end_sfl_writedata_to>),  //                          .sfl_writedata_to
		.avl_to_asmi_0_conduit_end_sfl_clk           (<connected-to-avl_to_asmi_0_conduit_end_sfl_clk>),           //                          .sfl_clk
		.avl_to_asmi_0_conduit_end_sfl_reset         (<connected-to-avl_to_asmi_0_conduit_end_sfl_reset>),         //                          .sfl_reset
		.clk_clk                                     (<connected-to-clk_clk>),                                     //                       clk.clk
		.clk_1_clk                                   (<connected-to-clk_1_clk>),                                   //                     clk_1.clk
		.fast_mem_address                            (<connected-to-fast_mem_address>),                            //                  fast_mem.address
		.fast_mem_read                               (<connected-to-fast_mem_read>),                               //                          .read
		.fast_mem_readdata                           (<connected-to-fast_mem_readdata>),                           //                          .readdata
		.fast_mem_readdatavalid                      (<connected-to-fast_mem_readdatavalid>),                      //                          .readdatavalid
		.fast_mem_waitrequest                        (<connected-to-fast_mem_waitrequest>),                        //                          .waitrequest
		.fast_mem_write                              (<connected-to-fast_mem_write>),                              //                          .write
		.fast_mem_writedata                          (<connected-to-fast_mem_writedata>),                          //                          .writedata
		.fast_mem_burstcount                         (<connected-to-fast_mem_burstcount>),                         //                          .burstcount
		.fast_mem_lock                               (<connected-to-fast_mem_lock>),                               //                          .lock
		.hip_ctrl_test_in                            (<connected-to-hip_ctrl_test_in>),                            //                  hip_ctrl.test_in
		.hip_ctrl_simu_mode_pipe                     (<connected-to-hip_ctrl_simu_mode_pipe>),                     //                          .simu_mode_pipe
		.hip_serial_rx_in0                           (<connected-to-hip_serial_rx_in0>),                           //                hip_serial.rx_in0
		.hip_serial_rx_in1                           (<connected-to-hip_serial_rx_in1>),                           //                          .rx_in1
		.hip_serial_rx_in2                           (<connected-to-hip_serial_rx_in2>),                           //                          .rx_in2
		.hip_serial_rx_in3                           (<connected-to-hip_serial_rx_in3>),                           //                          .rx_in3
		.hip_serial_tx_out0                          (<connected-to-hip_serial_tx_out0>),                          //                          .tx_out0
		.hip_serial_tx_out1                          (<connected-to-hip_serial_tx_out1>),                          //                          .tx_out1
		.hip_serial_tx_out2                          (<connected-to-hip_serial_tx_out2>),                          //                          .tx_out2
		.hip_serial_tx_out3                          (<connected-to-hip_serial_tx_out3>),                          //                          .tx_out3
		.memory_mem_a                                (<connected-to-memory_mem_a>),                                //                    memory.mem_a
		.memory_mem_ba                               (<connected-to-memory_mem_ba>),                               //                          .mem_ba
		.memory_mem_ck                               (<connected-to-memory_mem_ck>),                               //                          .mem_ck
		.memory_mem_ck_n                             (<connected-to-memory_mem_ck_n>),                             //                          .mem_ck_n
		.memory_mem_cke                              (<connected-to-memory_mem_cke>),                              //                          .mem_cke
		.memory_mem_cs_n                             (<connected-to-memory_mem_cs_n>),                             //                          .mem_cs_n
		.memory_mem_dm                               (<connected-to-memory_mem_dm>),                               //                          .mem_dm
		.memory_mem_ras_n                            (<connected-to-memory_mem_ras_n>),                            //                          .mem_ras_n
		.memory_mem_cas_n                            (<connected-to-memory_mem_cas_n>),                            //                          .mem_cas_n
		.memory_mem_we_n                             (<connected-to-memory_mem_we_n>),                             //                          .mem_we_n
		.memory_mem_reset_n                          (<connected-to-memory_mem_reset_n>),                          //                          .mem_reset_n
		.memory_mem_dq                               (<connected-to-memory_mem_dq>),                               //                          .mem_dq
		.memory_mem_dqs                              (<connected-to-memory_mem_dqs>),                              //                          .mem_dqs
		.memory_mem_dqs_n                            (<connected-to-memory_mem_dqs_n>),                            //                          .mem_dqs_n
		.memory_mem_odt                              (<connected-to-memory_mem_odt>),                              //                          .mem_odt
		.memory_1_mem_a                              (<connected-to-memory_1_mem_a>),                              //                  memory_1.mem_a
		.memory_1_mem_ba                             (<connected-to-memory_1_mem_ba>),                             //                          .mem_ba
		.memory_1_mem_ck                             (<connected-to-memory_1_mem_ck>),                             //                          .mem_ck
		.memory_1_mem_ck_n                           (<connected-to-memory_1_mem_ck_n>),                           //                          .mem_ck_n
		.memory_1_mem_cke                            (<connected-to-memory_1_mem_cke>),                            //                          .mem_cke
		.memory_1_mem_cs_n                           (<connected-to-memory_1_mem_cs_n>),                           //                          .mem_cs_n
		.memory_1_mem_dm                             (<connected-to-memory_1_mem_dm>),                             //                          .mem_dm
		.memory_1_mem_ras_n                          (<connected-to-memory_1_mem_ras_n>),                          //                          .mem_ras_n
		.memory_1_mem_cas_n                          (<connected-to-memory_1_mem_cas_n>),                          //                          .mem_cas_n
		.memory_1_mem_we_n                           (<connected-to-memory_1_mem_we_n>),                           //                          .mem_we_n
		.memory_1_mem_reset_n                        (<connected-to-memory_1_mem_reset_n>),                        //                          .mem_reset_n
		.memory_1_mem_dq                             (<connected-to-memory_1_mem_dq>),                             //                          .mem_dq
		.memory_1_mem_dqs                            (<connected-to-memory_1_mem_dqs>),                            //                          .mem_dqs
		.memory_1_mem_dqs_n                          (<connected-to-memory_1_mem_dqs_n>),                          //                          .mem_dqs_n
		.memory_1_mem_odt                            (<connected-to-memory_1_mem_odt>),                            //                          .mem_odt
		.mgmt_clk_clk                                (<connected-to-mgmt_clk_clk>),                                //                  mgmt_clk.clk
		.mgmt_rst_reset                              (<connected-to-mgmt_rst_reset>),                              //                  mgmt_rst.reset
		.oct_rzqin                                   (<connected-to-oct_rzqin>),                                   //                       oct.rzqin
		.oct_1_rzqin                                 (<connected-to-oct_1_rzqin>),                                 //                     oct_1.rzqin
		.pcie_npor_npor                              (<connected-to-pcie_npor_npor>),                              //                 pcie_npor.npor
		.pcie_npor_pin_perst                         (<connected-to-pcie_npor_pin_perst>),                         //                          .pin_perst
		.pcie_refclock_clk                           (<connected-to-pcie_refclock_clk>),                           //             pcie_refclock.clk
		.reconfig_xcvr_clk_clk                       (<connected-to-reconfig_xcvr_clk_clk>),                       //         reconfig_xcvr_clk.clk
		.reconfig_xcvr_rst_reset                     (<connected-to-reconfig_xcvr_rst_reset>),                     //         reconfig_xcvr_rst.reset
		.reset_reset_n                               (<connected-to-reset_reset_n>),                               //                     reset.reset_n
		.reset_1_reset_n                             (<connected-to-reset_1_reset_n>),                             //                   reset_1.reset_n
		.slow_mem_address                            (<connected-to-slow_mem_address>),                            //                  slow_mem.address
		.slow_mem_read                               (<connected-to-slow_mem_read>),                               //                          .read
		.slow_mem_readdata                           (<connected-to-slow_mem_readdata>),                           //                          .readdata
		.slow_mem_readdatavalid                      (<connected-to-slow_mem_readdatavalid>),                      //                          .readdatavalid
		.slow_mem_write                              (<connected-to-slow_mem_write>),                              //                          .write
		.slow_mem_writedata                          (<connected-to-slow_mem_writedata>),                          //                          .writedata
		.slow_mem_waitrequest                        (<connected-to-slow_mem_waitrequest>),                        //                          .waitrequest
		.slow_mem_burstcount                         (<connected-to-slow_mem_burstcount>),                         //                          .burstcount
		.slow_mem_lock                               (<connected-to-slow_mem_lock>)                                //                          .lock
	);

