# TCL File Generated by Component Editor 16.0
# Tue Apr 04 19:09:45 CDT 2017
# DO NOT MODIFY


# 
# move_engine "move_engine" v1.0
#  2017.04.04.19:09:45
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module move_engine
# 
set_module_property DESCRIPTION ""
set_module_property NAME move_engine
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME move_engine
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point slow_master
# 
add_interface slow_master avalon start
set_interface_property slow_master addressUnits SYMBOLS
set_interface_property slow_master associatedClock clk
set_interface_property slow_master associatedReset rst
set_interface_property slow_master bitsPerSymbol 8
set_interface_property slow_master burstOnBurstBoundariesOnly false
set_interface_property slow_master burstcountUnits WORDS
set_interface_property slow_master doStreamReads false
set_interface_property slow_master doStreamWrites false
set_interface_property slow_master holdTime 0
set_interface_property slow_master linewrapBursts false
set_interface_property slow_master maximumPendingReadTransactions 0
set_interface_property slow_master maximumPendingWriteTransactions 0
set_interface_property slow_master readLatency 0
set_interface_property slow_master readWaitTime 1
set_interface_property slow_master setupTime 0
set_interface_property slow_master timingUnits Cycles
set_interface_property slow_master writeWaitTime 0
set_interface_property slow_master ENABLED true
set_interface_property slow_master EXPORT_OF ""
set_interface_property slow_master PORT_NAME_MAP ""
set_interface_property slow_master CMSIS_SVD_VARIABLES ""
set_interface_property slow_master SVD_ADDRESS_GROUP ""

add_interface_port slow_master slow_master_address address Output 32
add_interface_port slow_master slow_master_read read Output 1
add_interface_port slow_master slow_master_readdata readdata Input 512
add_interface_port slow_master slow_master_readdatavalid readdatavalid Input 1
add_interface_port slow_master slow_master_write write Output 1
add_interface_port slow_master slow_master_writedata writedata Output 512
add_interface_port slow_master slow_master_waitrequest waitrequest Input 1
add_interface_port slow_master slow_master_burstcount burstcount Output 6
add_interface_port slow_master slow_master_lock lock Output 1


# 
# connection point fast_master
# 
add_interface fast_master avalon start
set_interface_property fast_master addressUnits SYMBOLS
set_interface_property fast_master associatedClock clk
set_interface_property fast_master associatedReset rst
set_interface_property fast_master bitsPerSymbol 8
set_interface_property fast_master burstOnBurstBoundariesOnly false
set_interface_property fast_master burstcountUnits WORDS
set_interface_property fast_master doStreamReads false
set_interface_property fast_master doStreamWrites false
set_interface_property fast_master holdTime 0
set_interface_property fast_master linewrapBursts false
set_interface_property fast_master maximumPendingReadTransactions 0
set_interface_property fast_master maximumPendingWriteTransactions 0
set_interface_property fast_master readLatency 0
set_interface_property fast_master readWaitTime 1
set_interface_property fast_master setupTime 0
set_interface_property fast_master timingUnits Cycles
set_interface_property fast_master writeWaitTime 0
set_interface_property fast_master ENABLED true
set_interface_property fast_master EXPORT_OF ""
set_interface_property fast_master PORT_NAME_MAP ""
set_interface_property fast_master CMSIS_SVD_VARIABLES ""
set_interface_property fast_master SVD_ADDRESS_GROUP ""

add_interface_port fast_master fast_master_address address Output 32
add_interface_port fast_master fast_master_read read Output 1
add_interface_port fast_master fast_master_readdata readdata Input 512
add_interface_port fast_master fast_master_readdatavalid readdatavalid Input 1
add_interface_port fast_master fast_master_waitrequest waitrequest Input 1
add_interface_port fast_master fast_master_write write Output 1
add_interface_port fast_master fast_master_writedata writedata Output 512
add_interface_port fast_master fast_master_burstcount burstcount Output 6
add_interface_port fast_master fast_master_lock lock Output 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1

