# _hw.tcl file for pcie_hip_avmm
package require -exact qsys 14.0

# module properties
set_module_property NAME {pcie_hip_avmm_export}
set_module_property DISPLAY_NAME {pcie_hip_avmm_export_display}

# default module properties
set_module_property VERSION {1.0}
set_module_property GROUP {default group}
set_module_property DESCRIPTION {default description}
set_module_property AUTHOR {author}

set_module_property COMPOSITION_CALLBACK compose
set_module_property opaque_address_map false

proc compose { } {
    # Instances and instance parameters
    # (disabled instances are intentionally culled)
    add_instance alt_xcvr_reconfig_0 alt_xcvr_reconfig 16.0
    set_instance_parameter_value alt_xcvr_reconfig_0 {number_of_reconfig_interfaces} {6}
    set_instance_parameter_value alt_xcvr_reconfig_0 {gui_split_sizes} {}
    set_instance_parameter_value alt_xcvr_reconfig_0 {enable_offset} {1}
    set_instance_parameter_value alt_xcvr_reconfig_0 {enable_dcd} {0}
    set_instance_parameter_value alt_xcvr_reconfig_0 {enable_dcd_power_up} {1}
    set_instance_parameter_value alt_xcvr_reconfig_0 {enable_analog} {1}
    set_instance_parameter_value alt_xcvr_reconfig_0 {enable_eyemon} {0}
    set_instance_parameter_value alt_xcvr_reconfig_0 {ber_en} {0}
    set_instance_parameter_value alt_xcvr_reconfig_0 {enable_dfe} {0}
    set_instance_parameter_value alt_xcvr_reconfig_0 {enable_adce} {1}
    set_instance_parameter_value alt_xcvr_reconfig_0 {enable_mif} {0}
    set_instance_parameter_value alt_xcvr_reconfig_0 {gui_enable_pll} {0}
    set_instance_parameter_value alt_xcvr_reconfig_0 {gui_cal_status_port} {0}

    add_instance clk_0 clock_source 16.0
    set_instance_parameter_value clk_0 {clockFrequency} {100.0}
    set_instance_parameter_value clk_0 {clockFrequencyKnown} {1}
    set_instance_parameter_value clk_0 {resetSynchronousEdges} {NONE}

    add_instance clk_1 clock_source 16.0
    set_instance_parameter_value clk_1 {clockFrequency} {100.0}
    set_instance_parameter_value clk_1 {clockFrequencyKnown} {1}
    set_instance_parameter_value clk_1 {resetSynchronousEdges} {NONE}

    add_instance ddr3_m2 altera_mem_if_ddr3_emif 16.0
    set_instance_parameter_value ddr3_m2 {MEM_VENDOR} {Micron}
    set_instance_parameter_value ddr3_m2 {MEM_FORMAT} {UNBUFFERED}
    set_instance_parameter_value ddr3_m2 {RDIMM_CONFIG} {0000000000000000}
    set_instance_parameter_value ddr3_m2 {LRDIMM_EXTENDED_CONFIG} {0x000000000000000000}
    set_instance_parameter_value ddr3_m2 {DISCRETE_FLY_BY} {1}
    set_instance_parameter_value ddr3_m2 {DEVICE_DEPTH} {1}
    set_instance_parameter_value ddr3_m2 {MEM_MIRROR_ADDRESSING} {10}
    set_instance_parameter_value ddr3_m2 {MEM_CLK_FREQ_MAX} {800.0}
    set_instance_parameter_value ddr3_m2 {MEM_ROW_ADDR_WIDTH} {16}
    set_instance_parameter_value ddr3_m2 {MEM_COL_ADDR_WIDTH} {10}
    set_instance_parameter_value ddr3_m2 {MEM_DQ_WIDTH} {64}
    set_instance_parameter_value ddr3_m2 {MEM_DQ_PER_DQS} {8}
    set_instance_parameter_value ddr3_m2 {MEM_BANKADDR_WIDTH} {3}
    set_instance_parameter_value ddr3_m2 {MEM_IF_DM_PINS_EN} {1}
    set_instance_parameter_value ddr3_m2 {MEM_IF_DQSN_EN} {1}
    set_instance_parameter_value ddr3_m2 {MEM_NUMBER_OF_DIMMS} {1}
    set_instance_parameter_value ddr3_m2 {MEM_NUMBER_OF_RANKS_PER_DIMM} {2}
    set_instance_parameter_value ddr3_m2 {MEM_NUMBER_OF_RANKS_PER_DEVICE} {1}
    set_instance_parameter_value ddr3_m2 {MEM_RANK_MULTIPLICATION_FACTOR} {1}
    set_instance_parameter_value ddr3_m2 {MEM_CK_WIDTH} {2}
    set_instance_parameter_value ddr3_m2 {MEM_CS_WIDTH} {1}
    set_instance_parameter_value ddr3_m2 {MEM_CLK_EN_WIDTH} {1}
    set_instance_parameter_value ddr3_m2 {ALTMEMPHY_COMPATIBLE_MODE} {0}
    set_instance_parameter_value ddr3_m2 {NEXTGEN} {1}
    set_instance_parameter_value ddr3_m2 {MEM_IF_BOARD_BASE_DELAY} {10}
    set_instance_parameter_value ddr3_m2 {MEM_IF_SIM_VALID_WINDOW} {0}
    set_instance_parameter_value ddr3_m2 {MEM_GUARANTEED_WRITE_INIT} {0}
    set_instance_parameter_value ddr3_m2 {MEM_VERBOSE} {1}
    set_instance_parameter_value ddr3_m2 {PINGPONGPHY_EN} {0}
    set_instance_parameter_value ddr3_m2 {DUPLICATE_AC} {0}
    set_instance_parameter_value ddr3_m2 {REFRESH_BURST_VALIDATION} {0}
    set_instance_parameter_value ddr3_m2 {AP_MODE_EN} {0}
    set_instance_parameter_value ddr3_m2 {AP_MODE} {0}
    set_instance_parameter_value ddr3_m2 {MEM_BL} {OTF}
    set_instance_parameter_value ddr3_m2 {MEM_BT} {Sequential}
    set_instance_parameter_value ddr3_m2 {MEM_ASR} {Manual}
    set_instance_parameter_value ddr3_m2 {MEM_SRT} {Normal}
    set_instance_parameter_value ddr3_m2 {MEM_PD} {DLL off}
    set_instance_parameter_value ddr3_m2 {MEM_DRV_STR} {RZQ/6}
    set_instance_parameter_value ddr3_m2 {MEM_DLL_EN} {1}
    set_instance_parameter_value ddr3_m2 {MEM_RTT_NOM} {RZQ/4}
    set_instance_parameter_value ddr3_m2 {MEM_RTT_WR} {RZQ/4}
    set_instance_parameter_value ddr3_m2 {MEM_WTCL} {8}
    set_instance_parameter_value ddr3_m2 {MEM_ATCL} {Disabled}
    set_instance_parameter_value ddr3_m2 {MEM_TCL} {11}
    set_instance_parameter_value ddr3_m2 {MEM_AUTO_LEVELING_MODE} {1}
    set_instance_parameter_value ddr3_m2 {MEM_USER_LEVELING_MODE} {Leveling}
    set_instance_parameter_value ddr3_m2 {MEM_INIT_EN} {0}
    set_instance_parameter_value ddr3_m2 {MEM_INIT_FILE} {}
    set_instance_parameter_value ddr3_m2 {DAT_DATA_WIDTH} {32}
    set_instance_parameter_value ddr3_m2 {TIMING_TIS} {170}
    set_instance_parameter_value ddr3_m2 {TIMING_TIH} {120}
    set_instance_parameter_value ddr3_m2 {TIMING_TDS} {10}
    set_instance_parameter_value ddr3_m2 {TIMING_TDH} {45}
    set_instance_parameter_value ddr3_m2 {TIMING_TDQSQ} {100}
    set_instance_parameter_value ddr3_m2 {TIMING_TQH} {0.38}
    set_instance_parameter_value ddr3_m2 {TIMING_TDQSCK} {225}
    set_instance_parameter_value ddr3_m2 {TIMING_TDQSCKDS} {450}
    set_instance_parameter_value ddr3_m2 {TIMING_TDQSCKDM} {900}
    set_instance_parameter_value ddr3_m2 {TIMING_TDQSCKDL} {1200}
    set_instance_parameter_value ddr3_m2 {TIMING_TDQSS} {0.27}
    set_instance_parameter_value ddr3_m2 {TIMING_TQSH} {0.4}
    set_instance_parameter_value ddr3_m2 {TIMING_TDSH} {0.18}
    set_instance_parameter_value ddr3_m2 {TIMING_TDSS} {0.18}
    set_instance_parameter_value ddr3_m2 {MEM_TINIT_US} {500}
    set_instance_parameter_value ddr3_m2 {MEM_TMRD_CK} {4}
    set_instance_parameter_value ddr3_m2 {MEM_TRAS_NS} {35.0}
    set_instance_parameter_value ddr3_m2 {MEM_TRCD_NS} {13.75}
    set_instance_parameter_value ddr3_m2 {MEM_TRP_NS} {13.75}
    set_instance_parameter_value ddr3_m2 {MEM_TREFI_US} {7.8}
    set_instance_parameter_value ddr3_m2 {MEM_TRFC_NS} {260.0}
    set_instance_parameter_value ddr3_m2 {CFG_TCCD_NS} {2.5}
    set_instance_parameter_value ddr3_m2 {MEM_TWR_NS} {15.0}
    set_instance_parameter_value ddr3_m2 {MEM_TWTR} {6}
    set_instance_parameter_value ddr3_m2 {MEM_TFAW_NS} {30.0}
    set_instance_parameter_value ddr3_m2 {MEM_TRRD_NS} {10.0}
    set_instance_parameter_value ddr3_m2 {MEM_TRTP_NS} {10.0}
    set_instance_parameter_value ddr3_m2 {RATE} {Quarter}
    set_instance_parameter_value ddr3_m2 {MEM_CLK_FREQ} {600.0}
    set_instance_parameter_value ddr3_m2 {USE_MEM_CLK_FREQ} {0}
    set_instance_parameter_value ddr3_m2 {FORCE_DQS_TRACKING} {AUTO}
    set_instance_parameter_value ddr3_m2 {FORCE_SHADOW_REGS} {AUTO}
    set_instance_parameter_value ddr3_m2 {MRS_MIRROR_PING_PONG_ATSO} {0}
    set_instance_parameter_value ddr3_m2 {PARSE_FRIENDLY_DEVICE_FAMILY_PARAM_VALID} {0}
    set_instance_parameter_value ddr3_m2 {PARSE_FRIENDLY_DEVICE_FAMILY_PARAM} {}
    set_instance_parameter_value ddr3_m2 {DEVICE_FAMILY_PARAM} {}
    set_instance_parameter_value ddr3_m2 {SPEED_GRADE} {4}
    set_instance_parameter_value ddr3_m2 {IS_ES_DEVICE} {0}
    set_instance_parameter_value ddr3_m2 {DISABLE_CHILD_MESSAGING} {0}
    set_instance_parameter_value ddr3_m2 {HARD_EMIF} {0}
    set_instance_parameter_value ddr3_m2 {HHP_HPS} {0}
    set_instance_parameter_value ddr3_m2 {HHP_HPS_VERIFICATION} {0}
    set_instance_parameter_value ddr3_m2 {HHP_HPS_SIMULATION} {0}
    set_instance_parameter_value ddr3_m2 {HPS_PROTOCOL} {DEFAULT}
    set_instance_parameter_value ddr3_m2 {CUT_NEW_FAMILY_TIMING} {1}
    set_instance_parameter_value ddr3_m2 {POWER_OF_TWO_BUS} {0}
    set_instance_parameter_value ddr3_m2 {SOPC_COMPAT_RESET} {0}
    set_instance_parameter_value ddr3_m2 {AVL_MAX_SIZE} {4}
    set_instance_parameter_value ddr3_m2 {BYTE_ENABLE} {1}
    set_instance_parameter_value ddr3_m2 {ENABLE_CTRL_AVALON_INTERFACE} {1}
    set_instance_parameter_value ddr3_m2 {CTL_DEEP_POWERDN_EN} {0}
    set_instance_parameter_value ddr3_m2 {CTL_SELF_REFRESH_EN} {0}
    set_instance_parameter_value ddr3_m2 {AUTO_POWERDN_EN} {0}
    set_instance_parameter_value ddr3_m2 {AUTO_PD_CYCLES} {0}
    set_instance_parameter_value ddr3_m2 {CTL_USR_REFRESH_EN} {0}
    set_instance_parameter_value ddr3_m2 {CTL_AUTOPCH_EN} {0}
    set_instance_parameter_value ddr3_m2 {CTL_ZQCAL_EN} {0}
    set_instance_parameter_value ddr3_m2 {ADDR_ORDER} {0}
    set_instance_parameter_value ddr3_m2 {CTL_LOOK_AHEAD_DEPTH} {4}
    set_instance_parameter_value ddr3_m2 {CONTROLLER_LATENCY} {5}
    set_instance_parameter_value ddr3_m2 {CFG_REORDER_DATA} {1}
    set_instance_parameter_value ddr3_m2 {STARVE_LIMIT} {10}
    set_instance_parameter_value ddr3_m2 {CTL_CSR_ENABLED} {1}
    set_instance_parameter_value ddr3_m2 {CTL_CSR_CONNECTION} {EXPORT}
    set_instance_parameter_value ddr3_m2 {CTL_ECC_ENABLED} {0}
    set_instance_parameter_value ddr3_m2 {CTL_HRB_ENABLED} {0}
    set_instance_parameter_value ddr3_m2 {CTL_ECC_AUTO_CORRECTION_ENABLED} {0}
    set_instance_parameter_value ddr3_m2 {MULTICAST_EN} {0}
    set_instance_parameter_value ddr3_m2 {CTL_DYNAMIC_BANK_ALLOCATION} {0}
    set_instance_parameter_value ddr3_m2 {CTL_DYNAMIC_BANK_NUM} {4}
    set_instance_parameter_value ddr3_m2 {DEBUG_MODE} {0}
    set_instance_parameter_value ddr3_m2 {ENABLE_BURST_MERGE} {0}
    set_instance_parameter_value ddr3_m2 {CTL_ENABLE_BURST_INTERRUPT} {0}
    set_instance_parameter_value ddr3_m2 {CTL_ENABLE_BURST_TERMINATE} {0}
    set_instance_parameter_value ddr3_m2 {LOCAL_ID_WIDTH} {8}
    set_instance_parameter_value ddr3_m2 {WRBUFFER_ADDR_WIDTH} {6}
    set_instance_parameter_value ddr3_m2 {MAX_PENDING_WR_CMD} {16}
    set_instance_parameter_value ddr3_m2 {MAX_PENDING_RD_CMD} {32}
    set_instance_parameter_value ddr3_m2 {USE_MM_ADAPTOR} {1}
    set_instance_parameter_value ddr3_m2 {USE_AXI_ADAPTOR} {0}
    set_instance_parameter_value ddr3_m2 {HCX_COMPAT_MODE} {0}
    set_instance_parameter_value ddr3_m2 {CTL_CMD_QUEUE_DEPTH} {8}
    set_instance_parameter_value ddr3_m2 {CTL_CSR_READ_ONLY} {1}
    set_instance_parameter_value ddr3_m2 {CFG_DATA_REORDERING_TYPE} {INTER_BANK}
    set_instance_parameter_value ddr3_m2 {NUM_OF_PORTS} {1}
    set_instance_parameter_value ddr3_m2 {ENABLE_BONDING} {0}
    set_instance_parameter_value ddr3_m2 {ENABLE_USER_ECC} {0}
    set_instance_parameter_value ddr3_m2 {AVL_DATA_WIDTH_PORT} {32 32 32 32 32 32}
    set_instance_parameter_value ddr3_m2 {PRIORITY_PORT} {1 1 1 1 1 1}
    set_instance_parameter_value ddr3_m2 {WEIGHT_PORT} {0 0 0 0 0 0}
    set_instance_parameter_value ddr3_m2 {CPORT_TYPE_PORT} {Bidirectional Bidirectional Bidirectional Bidirectional Bidirectional Bidirectional}
    set_instance_parameter_value ddr3_m2 {ENABLE_EMIT_BFM_MASTER} {0}
    set_instance_parameter_value ddr3_m2 {FORCE_SEQUENCER_TCL_DEBUG_MODE} {0}
    set_instance_parameter_value ddr3_m2 {ENABLE_SEQUENCER_MARGINING_ON_BY_DEFAULT} {0}
    set_instance_parameter_value ddr3_m2 {REF_CLK_FREQ} {100.0}
    set_instance_parameter_value ddr3_m2 {REF_CLK_FREQ_PARAM_VALID} {0}
    set_instance_parameter_value ddr3_m2 {REF_CLK_FREQ_MIN_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {REF_CLK_FREQ_MAX_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_DR_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_DR_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_DR_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_DR_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_DR_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_DR_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_MEM_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_MEM_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_MEM_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_MEM_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_MEM_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_MEM_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_WRITE_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_WRITE_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_WRITE_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_WRITE_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_WRITE_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_WRITE_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_ADDR_CMD_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_ADDR_CMD_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_ADDR_CMD_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_ADDR_CMD_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_ADDR_CMD_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_ADDR_CMD_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_HALF_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_HALF_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_HALF_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_HALF_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_HALF_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_HALF_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_NIOS_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_NIOS_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_NIOS_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_NIOS_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_NIOS_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_NIOS_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_CONFIG_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_CONFIG_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_CONFIG_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_CONFIG_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_CONFIG_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_CONFIG_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_P2C_READ_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_P2C_READ_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_P2C_READ_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_P2C_READ_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_P2C_READ_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_P2C_READ_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_C2P_WRITE_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_C2P_WRITE_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_C2P_WRITE_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_C2P_WRITE_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_C2P_WRITE_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_C2P_WRITE_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_HR_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_HR_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_HR_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_HR_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_HR_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_HR_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_PHY_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_PHY_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_PHY_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_PHY_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_PHY_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_AFI_PHY_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_CLK_PARAM_VALID} {0}
    set_instance_parameter_value ddr3_m2 {ENABLE_EXTRA_REPORTING} {0}
    set_instance_parameter_value ddr3_m2 {NUM_EXTRA_REPORT_PATH} {10}
    set_instance_parameter_value ddr3_m2 {ENABLE_ISS_PROBES} {0}
    set_instance_parameter_value ddr3_m2 {CALIB_REG_WIDTH} {8}
    set_instance_parameter_value ddr3_m2 {USE_SEQUENCER_BFM} {0}
    set_instance_parameter_value ddr3_m2 {PLL_SHARING_MODE} {None}
    set_instance_parameter_value ddr3_m2 {NUM_PLL_SHARING_INTERFACES} {1}
    set_instance_parameter_value ddr3_m2 {EXPORT_AFI_HALF_CLK} {0}
    set_instance_parameter_value ddr3_m2 {ABSTRACT_REAL_COMPARE_TEST} {0}
    set_instance_parameter_value ddr3_m2 {INCLUDE_BOARD_DELAY_MODEL} {0}
    set_instance_parameter_value ddr3_m2 {INCLUDE_MULTIRANK_BOARD_DELAY_MODEL} {0}
    set_instance_parameter_value ddr3_m2 {USE_FAKE_PHY} {0}
    set_instance_parameter_value ddr3_m2 {FORCE_MAX_LATENCY_COUNT_WIDTH} {0}
    set_instance_parameter_value ddr3_m2 {ENABLE_NON_DESTRUCTIVE_CALIB} {0}
    set_instance_parameter_value ddr3_m2 {FIX_READ_LATENCY} {8}
    set_instance_parameter_value ddr3_m2 {ENABLE_DELAY_CHAIN_WRITE} {0}
    set_instance_parameter_value ddr3_m2 {TRACKING_ERROR_TEST} {0}
    set_instance_parameter_value ddr3_m2 {TRACKING_WATCH_TEST} {0}
    set_instance_parameter_value ddr3_m2 {MARGIN_VARIATION_TEST} {0}
    set_instance_parameter_value ddr3_m2 {AC_ROM_USER_ADD_0} {0_0000_0000_0000}
    set_instance_parameter_value ddr3_m2 {AC_ROM_USER_ADD_1} {0_0000_0000_1000}
    set_instance_parameter_value ddr3_m2 {TREFI} {35100}
    set_instance_parameter_value ddr3_m2 {REFRESH_INTERVAL} {15000}
    set_instance_parameter_value ddr3_m2 {ENABLE_NON_DES_CAL_TEST} {0}
    set_instance_parameter_value ddr3_m2 {TRFC} {350}
    set_instance_parameter_value ddr3_m2 {ENABLE_NON_DES_CAL} {0}
    set_instance_parameter_value ddr3_m2 {EXTRA_SETTINGS} {}
    set_instance_parameter_value ddr3_m2 {MEM_DEVICE} {MISSING_MODEL}
    set_instance_parameter_value ddr3_m2 {FORCE_SYNTHESIS_LANGUAGE} {}
    set_instance_parameter_value ddr3_m2 {FORCED_NUM_WRITE_FR_CYCLE_SHIFTS} {0}
    set_instance_parameter_value ddr3_m2 {SEQUENCER_TYPE} {NIOS}
    set_instance_parameter_value ddr3_m2 {ADVERTIZE_SEQUENCER_SW_BUILD_FILES} {0}
    set_instance_parameter_value ddr3_m2 {FORCED_NON_LDC_ADDR_CMD_MEM_CK_INVERT} {0}
    set_instance_parameter_value ddr3_m2 {PHY_ONLY} {0}
    set_instance_parameter_value ddr3_m2 {SEQ_MODE} {0}
    set_instance_parameter_value ddr3_m2 {ADVANCED_CK_PHASES} {0}
    set_instance_parameter_value ddr3_m2 {COMMAND_PHASE} {0.0}
    set_instance_parameter_value ddr3_m2 {MEM_CK_PHASE} {0.0}
    set_instance_parameter_value ddr3_m2 {P2C_READ_CLOCK_ADD_PHASE} {0.0}
    set_instance_parameter_value ddr3_m2 {C2P_WRITE_CLOCK_ADD_PHASE} {0.0}
    set_instance_parameter_value ddr3_m2 {ACV_PHY_CLK_ADD_FR_PHASE} {0.0}
    set_instance_parameter_value ddr3_m2 {MEM_VOLTAGE} {1.5V DDR3}
    set_instance_parameter_value ddr3_m2 {PLL_LOCATION} {Top_Bottom}
    set_instance_parameter_value ddr3_m2 {SKIP_MEM_INIT} {1}
    set_instance_parameter_value ddr3_m2 {READ_DQ_DQS_CLOCK_SOURCE} {INVERTED_DQS_BUS}
    set_instance_parameter_value ddr3_m2 {DQ_INPUT_REG_USE_CLKN} {0}
    set_instance_parameter_value ddr3_m2 {DQS_DQSN_MODE} {DIFFERENTIAL}
    set_instance_parameter_value ddr3_m2 {AFI_DEBUG_INFO_WIDTH} {32}
    set_instance_parameter_value ddr3_m2 {CALIBRATION_MODE} {Skip}
    set_instance_parameter_value ddr3_m2 {NIOS_ROM_DATA_WIDTH} {32}
    set_instance_parameter_value ddr3_m2 {READ_FIFO_SIZE} {8}
    set_instance_parameter_value ddr3_m2 {PHY_CSR_ENABLED} {0}
    set_instance_parameter_value ddr3_m2 {PHY_CSR_CONNECTION} {INTERNAL_JTAG}
    set_instance_parameter_value ddr3_m2 {USER_DEBUG_LEVEL} {1}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_DERATE_METHOD} {AUTO}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_CK_CKN_SLEW_RATE} {2.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_AC_SLEW_RATE} {1.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_DQS_DQSN_SLEW_RATE} {2.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_DQ_SLEW_RATE} {1.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_TIS} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_TIH} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_TDS} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_TDH} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_ISI_METHOD} {AUTO}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_AC_EYE_REDUCTION_SU} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_AC_EYE_REDUCTION_H} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_DQ_EYE_REDUCTION} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_DELTA_DQS_ARRIVAL_TIME} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_READ_DQ_EYE_REDUCTION} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_DELTA_READ_DQS_ARRIVAL_TIME} {0.0}
    set_instance_parameter_value ddr3_m2 {PACKAGE_DESKEW} {0}
    set_instance_parameter_value ddr3_m2 {AC_PACKAGE_DESKEW} {0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_MAX_CK_DELAY} {0.6}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_MAX_DQS_DELAY} {0.6}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_SKEW_CKDQS_DIMM_MIN} {-0.01}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_SKEW_CKDQS_DIMM_MAX} {0.01}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_SKEW_BETWEEN_DIMMS} {0.05}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_SKEW_WITHIN_DQS} {0.02}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_SKEW_BETWEEN_DQS} {0.02}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_DQ_TO_DQS_SKEW} {0.0}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_AC_SKEW} {0.02}
    set_instance_parameter_value ddr3_m2 {TIMING_BOARD_AC_TO_CK_SKEW} {0.0}
    set_instance_parameter_value ddr3_m2 {ENABLE_EXPORT_SEQ_DEBUG_BRIDGE} {1}
    set_instance_parameter_value ddr3_m2 {CORE_DEBUG_CONNECTION} {EXPORT}
    set_instance_parameter_value ddr3_m2 {ADD_EXTERNAL_SEQ_DEBUG_NIOS} {0}
    set_instance_parameter_value ddr3_m2 {ED_EXPORT_SEQ_DEBUG} {0}
    set_instance_parameter_value ddr3_m2 {ADD_EFFICIENCY_MONITOR} {0}
    set_instance_parameter_value ddr3_m2 {ENABLE_ABS_RAM_MEM_INIT} {0}
    set_instance_parameter_value ddr3_m2 {ABS_RAM_MEM_INIT_FILENAME} {meminit}
    set_instance_parameter_value ddr3_m2 {DLL_SHARING_MODE} {None}
    set_instance_parameter_value ddr3_m2 {NUM_DLL_SHARING_INTERFACES} {1}
    set_instance_parameter_value ddr3_m2 {OCT_SHARING_MODE} {None}
    set_instance_parameter_value ddr3_m2 {NUM_OCT_SHARING_INTERFACES} {1}

    add_instance ddr3_m4 altera_mem_if_ddr3_emif 16.0
    set_instance_parameter_value ddr3_m4 {MEM_VENDOR} {Micron}
    set_instance_parameter_value ddr3_m4 {MEM_FORMAT} {UNBUFFERED}
    set_instance_parameter_value ddr3_m4 {RDIMM_CONFIG} {0000000000000000}
    set_instance_parameter_value ddr3_m4 {LRDIMM_EXTENDED_CONFIG} {0x000000000000000000}
    set_instance_parameter_value ddr3_m4 {DISCRETE_FLY_BY} {1}
    set_instance_parameter_value ddr3_m4 {DEVICE_DEPTH} {1}
    set_instance_parameter_value ddr3_m4 {MEM_MIRROR_ADDRESSING} {10}
    set_instance_parameter_value ddr3_m4 {MEM_CLK_FREQ_MAX} {800.0}
    set_instance_parameter_value ddr3_m4 {MEM_ROW_ADDR_WIDTH} {16}
    set_instance_parameter_value ddr3_m4 {MEM_COL_ADDR_WIDTH} {10}
    set_instance_parameter_value ddr3_m4 {MEM_DQ_WIDTH} {64}
    set_instance_parameter_value ddr3_m4 {MEM_DQ_PER_DQS} {8}
    set_instance_parameter_value ddr3_m4 {MEM_BANKADDR_WIDTH} {3}
    set_instance_parameter_value ddr3_m4 {MEM_IF_DM_PINS_EN} {1}
    set_instance_parameter_value ddr3_m4 {MEM_IF_DQSN_EN} {1}
    set_instance_parameter_value ddr3_m4 {MEM_NUMBER_OF_DIMMS} {1}
    set_instance_parameter_value ddr3_m4 {MEM_NUMBER_OF_RANKS_PER_DIMM} {2}
    set_instance_parameter_value ddr3_m4 {MEM_NUMBER_OF_RANKS_PER_DEVICE} {1}
    set_instance_parameter_value ddr3_m4 {MEM_RANK_MULTIPLICATION_FACTOR} {1}
    set_instance_parameter_value ddr3_m4 {MEM_CK_WIDTH} {2}
    set_instance_parameter_value ddr3_m4 {MEM_CS_WIDTH} {1}
    set_instance_parameter_value ddr3_m4 {MEM_CLK_EN_WIDTH} {1}
    set_instance_parameter_value ddr3_m4 {ALTMEMPHY_COMPATIBLE_MODE} {0}
    set_instance_parameter_value ddr3_m4 {NEXTGEN} {1}
    set_instance_parameter_value ddr3_m4 {MEM_IF_BOARD_BASE_DELAY} {10}
    set_instance_parameter_value ddr3_m4 {MEM_IF_SIM_VALID_WINDOW} {0}
    set_instance_parameter_value ddr3_m4 {MEM_GUARANTEED_WRITE_INIT} {0}
    set_instance_parameter_value ddr3_m4 {MEM_VERBOSE} {1}
    set_instance_parameter_value ddr3_m4 {PINGPONGPHY_EN} {0}
    set_instance_parameter_value ddr3_m4 {DUPLICATE_AC} {0}
    set_instance_parameter_value ddr3_m4 {REFRESH_BURST_VALIDATION} {0}
    set_instance_parameter_value ddr3_m4 {AP_MODE_EN} {0}
    set_instance_parameter_value ddr3_m4 {AP_MODE} {0}
    set_instance_parameter_value ddr3_m4 {MEM_BL} {OTF}
    set_instance_parameter_value ddr3_m4 {MEM_BT} {Sequential}
    set_instance_parameter_value ddr3_m4 {MEM_ASR} {Manual}
    set_instance_parameter_value ddr3_m4 {MEM_SRT} {Normal}
    set_instance_parameter_value ddr3_m4 {MEM_PD} {DLL off}
    set_instance_parameter_value ddr3_m4 {MEM_DRV_STR} {RZQ/6}
    set_instance_parameter_value ddr3_m4 {MEM_DLL_EN} {1}
    set_instance_parameter_value ddr3_m4 {MEM_RTT_NOM} {RZQ/4}
    set_instance_parameter_value ddr3_m4 {MEM_RTT_WR} {RZQ/4}
    set_instance_parameter_value ddr3_m4 {MEM_WTCL} {8}
    set_instance_parameter_value ddr3_m4 {MEM_ATCL} {Disabled}
    set_instance_parameter_value ddr3_m4 {MEM_TCL} {11}
    set_instance_parameter_value ddr3_m4 {MEM_AUTO_LEVELING_MODE} {1}
    set_instance_parameter_value ddr3_m4 {MEM_USER_LEVELING_MODE} {Leveling}
    set_instance_parameter_value ddr3_m4 {MEM_INIT_EN} {0}
    set_instance_parameter_value ddr3_m4 {MEM_INIT_FILE} {}
    set_instance_parameter_value ddr3_m4 {DAT_DATA_WIDTH} {32}
    set_instance_parameter_value ddr3_m4 {TIMING_TIS} {170}
    set_instance_parameter_value ddr3_m4 {TIMING_TIH} {120}
    set_instance_parameter_value ddr3_m4 {TIMING_TDS} {10}
    set_instance_parameter_value ddr3_m4 {TIMING_TDH} {45}
    set_instance_parameter_value ddr3_m4 {TIMING_TDQSQ} {100}
    set_instance_parameter_value ddr3_m4 {TIMING_TQH} {0.38}
    set_instance_parameter_value ddr3_m4 {TIMING_TDQSCK} {225}
    set_instance_parameter_value ddr3_m4 {TIMING_TDQSCKDS} {450}
    set_instance_parameter_value ddr3_m4 {TIMING_TDQSCKDM} {900}
    set_instance_parameter_value ddr3_m4 {TIMING_TDQSCKDL} {1200}
    set_instance_parameter_value ddr3_m4 {TIMING_TDQSS} {0.27}
    set_instance_parameter_value ddr3_m4 {TIMING_TQSH} {0.4}
    set_instance_parameter_value ddr3_m4 {TIMING_TDSH} {0.18}
    set_instance_parameter_value ddr3_m4 {TIMING_TDSS} {0.18}
    set_instance_parameter_value ddr3_m4 {MEM_TINIT_US} {500}
    set_instance_parameter_value ddr3_m4 {MEM_TMRD_CK} {4}
    set_instance_parameter_value ddr3_m4 {MEM_TRAS_NS} {35.0}
    set_instance_parameter_value ddr3_m4 {MEM_TRCD_NS} {13.75}
    set_instance_parameter_value ddr3_m4 {MEM_TRP_NS} {13.75}
    set_instance_parameter_value ddr3_m4 {MEM_TREFI_US} {7.8}
    set_instance_parameter_value ddr3_m4 {MEM_TRFC_NS} {260.0}
    set_instance_parameter_value ddr3_m4 {CFG_TCCD_NS} {2.5}
    set_instance_parameter_value ddr3_m4 {MEM_TWR_NS} {15.0}
    set_instance_parameter_value ddr3_m4 {MEM_TWTR} {6}
    set_instance_parameter_value ddr3_m4 {MEM_TFAW_NS} {30.0}
    set_instance_parameter_value ddr3_m4 {MEM_TRRD_NS} {10.0}
    set_instance_parameter_value ddr3_m4 {MEM_TRTP_NS} {10.0}
    set_instance_parameter_value ddr3_m4 {RATE} {Quarter}
    set_instance_parameter_value ddr3_m4 {MEM_CLK_FREQ} {600.0}
    set_instance_parameter_value ddr3_m4 {USE_MEM_CLK_FREQ} {0}
    set_instance_parameter_value ddr3_m4 {FORCE_DQS_TRACKING} {AUTO}
    set_instance_parameter_value ddr3_m4 {FORCE_SHADOW_REGS} {AUTO}
    set_instance_parameter_value ddr3_m4 {MRS_MIRROR_PING_PONG_ATSO} {0}
    set_instance_parameter_value ddr3_m4 {PARSE_FRIENDLY_DEVICE_FAMILY_PARAM_VALID} {0}
    set_instance_parameter_value ddr3_m4 {PARSE_FRIENDLY_DEVICE_FAMILY_PARAM} {}
    set_instance_parameter_value ddr3_m4 {DEVICE_FAMILY_PARAM} {}
    set_instance_parameter_value ddr3_m4 {SPEED_GRADE} {4}
    set_instance_parameter_value ddr3_m4 {IS_ES_DEVICE} {0}
    set_instance_parameter_value ddr3_m4 {DISABLE_CHILD_MESSAGING} {0}
    set_instance_parameter_value ddr3_m4 {HARD_EMIF} {0}
    set_instance_parameter_value ddr3_m4 {HHP_HPS} {0}
    set_instance_parameter_value ddr3_m4 {HHP_HPS_VERIFICATION} {0}
    set_instance_parameter_value ddr3_m4 {HHP_HPS_SIMULATION} {0}
    set_instance_parameter_value ddr3_m4 {HPS_PROTOCOL} {DEFAULT}
    set_instance_parameter_value ddr3_m4 {CUT_NEW_FAMILY_TIMING} {1}
    set_instance_parameter_value ddr3_m4 {POWER_OF_TWO_BUS} {0}
    set_instance_parameter_value ddr3_m4 {SOPC_COMPAT_RESET} {0}
    set_instance_parameter_value ddr3_m4 {AVL_MAX_SIZE} {4}
    set_instance_parameter_value ddr3_m4 {BYTE_ENABLE} {1}
    set_instance_parameter_value ddr3_m4 {ENABLE_CTRL_AVALON_INTERFACE} {1}
    set_instance_parameter_value ddr3_m4 {CTL_DEEP_POWERDN_EN} {0}
    set_instance_parameter_value ddr3_m4 {CTL_SELF_REFRESH_EN} {0}
    set_instance_parameter_value ddr3_m4 {AUTO_POWERDN_EN} {0}
    set_instance_parameter_value ddr3_m4 {AUTO_PD_CYCLES} {0}
    set_instance_parameter_value ddr3_m4 {CTL_USR_REFRESH_EN} {0}
    set_instance_parameter_value ddr3_m4 {CTL_AUTOPCH_EN} {0}
    set_instance_parameter_value ddr3_m4 {CTL_ZQCAL_EN} {0}
    set_instance_parameter_value ddr3_m4 {ADDR_ORDER} {0}
    set_instance_parameter_value ddr3_m4 {CTL_LOOK_AHEAD_DEPTH} {4}
    set_instance_parameter_value ddr3_m4 {CONTROLLER_LATENCY} {5}
    set_instance_parameter_value ddr3_m4 {CFG_REORDER_DATA} {1}
    set_instance_parameter_value ddr3_m4 {STARVE_LIMIT} {10}
    set_instance_parameter_value ddr3_m4 {CTL_CSR_ENABLED} {1}
    set_instance_parameter_value ddr3_m4 {CTL_CSR_CONNECTION} {EXPORT}
    set_instance_parameter_value ddr3_m4 {CTL_ECC_ENABLED} {0}
    set_instance_parameter_value ddr3_m4 {CTL_HRB_ENABLED} {0}
    set_instance_parameter_value ddr3_m4 {CTL_ECC_AUTO_CORRECTION_ENABLED} {0}
    set_instance_parameter_value ddr3_m4 {MULTICAST_EN} {0}
    set_instance_parameter_value ddr3_m4 {CTL_DYNAMIC_BANK_ALLOCATION} {0}
    set_instance_parameter_value ddr3_m4 {CTL_DYNAMIC_BANK_NUM} {4}
    set_instance_parameter_value ddr3_m4 {DEBUG_MODE} {0}
    set_instance_parameter_value ddr3_m4 {ENABLE_BURST_MERGE} {0}
    set_instance_parameter_value ddr3_m4 {CTL_ENABLE_BURST_INTERRUPT} {0}
    set_instance_parameter_value ddr3_m4 {CTL_ENABLE_BURST_TERMINATE} {0}
    set_instance_parameter_value ddr3_m4 {LOCAL_ID_WIDTH} {8}
    set_instance_parameter_value ddr3_m4 {WRBUFFER_ADDR_WIDTH} {6}
    set_instance_parameter_value ddr3_m4 {MAX_PENDING_WR_CMD} {16}
    set_instance_parameter_value ddr3_m4 {MAX_PENDING_RD_CMD} {32}
    set_instance_parameter_value ddr3_m4 {USE_MM_ADAPTOR} {1}
    set_instance_parameter_value ddr3_m4 {USE_AXI_ADAPTOR} {0}
    set_instance_parameter_value ddr3_m4 {HCX_COMPAT_MODE} {0}
    set_instance_parameter_value ddr3_m4 {CTL_CMD_QUEUE_DEPTH} {8}
    set_instance_parameter_value ddr3_m4 {CTL_CSR_READ_ONLY} {1}
    set_instance_parameter_value ddr3_m4 {CFG_DATA_REORDERING_TYPE} {INTER_BANK}
    set_instance_parameter_value ddr3_m4 {NUM_OF_PORTS} {1}
    set_instance_parameter_value ddr3_m4 {ENABLE_BONDING} {0}
    set_instance_parameter_value ddr3_m4 {ENABLE_USER_ECC} {0}
    set_instance_parameter_value ddr3_m4 {AVL_DATA_WIDTH_PORT} {32 32 32 32 32 32}
    set_instance_parameter_value ddr3_m4 {PRIORITY_PORT} {1 1 1 1 1 1}
    set_instance_parameter_value ddr3_m4 {WEIGHT_PORT} {0 0 0 0 0 0}
    set_instance_parameter_value ddr3_m4 {CPORT_TYPE_PORT} {Bidirectional Bidirectional Bidirectional Bidirectional Bidirectional Bidirectional}
    set_instance_parameter_value ddr3_m4 {ENABLE_EMIT_BFM_MASTER} {0}
    set_instance_parameter_value ddr3_m4 {FORCE_SEQUENCER_TCL_DEBUG_MODE} {0}
    set_instance_parameter_value ddr3_m4 {ENABLE_SEQUENCER_MARGINING_ON_BY_DEFAULT} {0}
    set_instance_parameter_value ddr3_m4 {REF_CLK_FREQ} {100.0}
    set_instance_parameter_value ddr3_m4 {REF_CLK_FREQ_PARAM_VALID} {0}
    set_instance_parameter_value ddr3_m4 {REF_CLK_FREQ_MIN_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {REF_CLK_FREQ_MAX_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_DR_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_DR_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_DR_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_DR_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_DR_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_DR_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_MEM_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_MEM_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_MEM_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_MEM_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_MEM_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_MEM_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_WRITE_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_WRITE_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_WRITE_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_WRITE_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_WRITE_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_WRITE_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_ADDR_CMD_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_ADDR_CMD_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_ADDR_CMD_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_ADDR_CMD_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_ADDR_CMD_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_ADDR_CMD_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_HALF_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_HALF_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_HALF_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_HALF_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_HALF_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_HALF_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_NIOS_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_NIOS_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_NIOS_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_NIOS_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_NIOS_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_NIOS_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_CONFIG_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_CONFIG_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_CONFIG_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_CONFIG_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_CONFIG_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_CONFIG_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_P2C_READ_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_P2C_READ_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_P2C_READ_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_P2C_READ_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_P2C_READ_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_P2C_READ_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_C2P_WRITE_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_C2P_WRITE_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_C2P_WRITE_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_C2P_WRITE_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_C2P_WRITE_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_C2P_WRITE_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_HR_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_HR_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_HR_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_HR_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_HR_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_HR_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_PHY_CLK_FREQ_PARAM} {0.0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_PHY_CLK_FREQ_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_PHY_CLK_PHASE_PS_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_PHY_CLK_PHASE_PS_SIM_STR_PARAM} {}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_PHY_CLK_MULT_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_AFI_PHY_CLK_DIV_PARAM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_CLK_PARAM_VALID} {0}
    set_instance_parameter_value ddr3_m4 {ENABLE_EXTRA_REPORTING} {0}
    set_instance_parameter_value ddr3_m4 {NUM_EXTRA_REPORT_PATH} {10}
    set_instance_parameter_value ddr3_m4 {ENABLE_ISS_PROBES} {0}
    set_instance_parameter_value ddr3_m4 {CALIB_REG_WIDTH} {8}
    set_instance_parameter_value ddr3_m4 {USE_SEQUENCER_BFM} {0}
    set_instance_parameter_value ddr3_m4 {PLL_SHARING_MODE} {None}
    set_instance_parameter_value ddr3_m4 {NUM_PLL_SHARING_INTERFACES} {1}
    set_instance_parameter_value ddr3_m4 {EXPORT_AFI_HALF_CLK} {0}
    set_instance_parameter_value ddr3_m4 {ABSTRACT_REAL_COMPARE_TEST} {0}
    set_instance_parameter_value ddr3_m4 {INCLUDE_BOARD_DELAY_MODEL} {0}
    set_instance_parameter_value ddr3_m4 {INCLUDE_MULTIRANK_BOARD_DELAY_MODEL} {0}
    set_instance_parameter_value ddr3_m4 {USE_FAKE_PHY} {0}
    set_instance_parameter_value ddr3_m4 {FORCE_MAX_LATENCY_COUNT_WIDTH} {0}
    set_instance_parameter_value ddr3_m4 {ENABLE_NON_DESTRUCTIVE_CALIB} {0}
    set_instance_parameter_value ddr3_m4 {FIX_READ_LATENCY} {8}
    set_instance_parameter_value ddr3_m4 {ENABLE_DELAY_CHAIN_WRITE} {0}
    set_instance_parameter_value ddr3_m4 {TRACKING_ERROR_TEST} {0}
    set_instance_parameter_value ddr3_m4 {TRACKING_WATCH_TEST} {0}
    set_instance_parameter_value ddr3_m4 {MARGIN_VARIATION_TEST} {0}
    set_instance_parameter_value ddr3_m4 {AC_ROM_USER_ADD_0} {0_0000_0000_0000}
    set_instance_parameter_value ddr3_m4 {AC_ROM_USER_ADD_1} {0_0000_0000_1000}
    set_instance_parameter_value ddr3_m4 {TREFI} {35100}
    set_instance_parameter_value ddr3_m4 {REFRESH_INTERVAL} {15000}
    set_instance_parameter_value ddr3_m4 {ENABLE_NON_DES_CAL_TEST} {0}
    set_instance_parameter_value ddr3_m4 {TRFC} {350}
    set_instance_parameter_value ddr3_m4 {ENABLE_NON_DES_CAL} {0}
    set_instance_parameter_value ddr3_m4 {EXTRA_SETTINGS} {}
    set_instance_parameter_value ddr3_m4 {MEM_DEVICE} {MISSING_MODEL}
    set_instance_parameter_value ddr3_m4 {FORCE_SYNTHESIS_LANGUAGE} {}
    set_instance_parameter_value ddr3_m4 {FORCED_NUM_WRITE_FR_CYCLE_SHIFTS} {0}
    set_instance_parameter_value ddr3_m4 {SEQUENCER_TYPE} {NIOS}
    set_instance_parameter_value ddr3_m4 {ADVERTIZE_SEQUENCER_SW_BUILD_FILES} {0}
    set_instance_parameter_value ddr3_m4 {FORCED_NON_LDC_ADDR_CMD_MEM_CK_INVERT} {0}
    set_instance_parameter_value ddr3_m4 {PHY_ONLY} {0}
    set_instance_parameter_value ddr3_m4 {SEQ_MODE} {0}
    set_instance_parameter_value ddr3_m4 {ADVANCED_CK_PHASES} {0}
    set_instance_parameter_value ddr3_m4 {COMMAND_PHASE} {0.0}
    set_instance_parameter_value ddr3_m4 {MEM_CK_PHASE} {0.0}
    set_instance_parameter_value ddr3_m4 {P2C_READ_CLOCK_ADD_PHASE} {0.0}
    set_instance_parameter_value ddr3_m4 {C2P_WRITE_CLOCK_ADD_PHASE} {0.0}
    set_instance_parameter_value ddr3_m4 {ACV_PHY_CLK_ADD_FR_PHASE} {0.0}
    set_instance_parameter_value ddr3_m4 {MEM_VOLTAGE} {1.5V DDR3}
    set_instance_parameter_value ddr3_m4 {PLL_LOCATION} {Top_Bottom}
    set_instance_parameter_value ddr3_m4 {SKIP_MEM_INIT} {1}
    set_instance_parameter_value ddr3_m4 {READ_DQ_DQS_CLOCK_SOURCE} {INVERTED_DQS_BUS}
    set_instance_parameter_value ddr3_m4 {DQ_INPUT_REG_USE_CLKN} {0}
    set_instance_parameter_value ddr3_m4 {DQS_DQSN_MODE} {DIFFERENTIAL}
    set_instance_parameter_value ddr3_m4 {AFI_DEBUG_INFO_WIDTH} {32}
    set_instance_parameter_value ddr3_m4 {CALIBRATION_MODE} {Skip}
    set_instance_parameter_value ddr3_m4 {NIOS_ROM_DATA_WIDTH} {32}
    set_instance_parameter_value ddr3_m4 {READ_FIFO_SIZE} {8}
    set_instance_parameter_value ddr3_m4 {PHY_CSR_ENABLED} {0}
    set_instance_parameter_value ddr3_m4 {PHY_CSR_CONNECTION} {INTERNAL_JTAG}
    set_instance_parameter_value ddr3_m4 {USER_DEBUG_LEVEL} {1}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_DERATE_METHOD} {AUTO}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_CK_CKN_SLEW_RATE} {2.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_AC_SLEW_RATE} {1.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_DQS_DQSN_SLEW_RATE} {2.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_DQ_SLEW_RATE} {1.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_TIS} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_TIH} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_TDS} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_TDH} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_ISI_METHOD} {AUTO}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_AC_EYE_REDUCTION_SU} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_AC_EYE_REDUCTION_H} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_DQ_EYE_REDUCTION} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_DELTA_DQS_ARRIVAL_TIME} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_READ_DQ_EYE_REDUCTION} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_DELTA_READ_DQS_ARRIVAL_TIME} {0.0}
    set_instance_parameter_value ddr3_m4 {PACKAGE_DESKEW} {0}
    set_instance_parameter_value ddr3_m4 {AC_PACKAGE_DESKEW} {0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_MAX_CK_DELAY} {0.6}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_MAX_DQS_DELAY} {0.6}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_SKEW_CKDQS_DIMM_MIN} {-0.01}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_SKEW_CKDQS_DIMM_MAX} {0.01}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_SKEW_BETWEEN_DIMMS} {0.05}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_SKEW_WITHIN_DQS} {0.02}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_SKEW_BETWEEN_DQS} {0.02}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_DQ_TO_DQS_SKEW} {0.0}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_AC_SKEW} {0.02}
    set_instance_parameter_value ddr3_m4 {TIMING_BOARD_AC_TO_CK_SKEW} {0.0}
    set_instance_parameter_value ddr3_m4 {ENABLE_EXPORT_SEQ_DEBUG_BRIDGE} {1}
    set_instance_parameter_value ddr3_m4 {CORE_DEBUG_CONNECTION} {EXPORT}
    set_instance_parameter_value ddr3_m4 {ADD_EXTERNAL_SEQ_DEBUG_NIOS} {0}
    set_instance_parameter_value ddr3_m4 {ED_EXPORT_SEQ_DEBUG} {0}
    set_instance_parameter_value ddr3_m4 {ADD_EFFICIENCY_MONITOR} {0}
    set_instance_parameter_value ddr3_m4 {ENABLE_ABS_RAM_MEM_INIT} {0}
    set_instance_parameter_value ddr3_m4 {ABS_RAM_MEM_INIT_FILENAME} {meminit}
    set_instance_parameter_value ddr3_m4 {DLL_SHARING_MODE} {None}
    set_instance_parameter_value ddr3_m4 {NUM_DLL_SHARING_INTERFACES} {1}
    set_instance_parameter_value ddr3_m4 {OCT_SHARING_MODE} {None}
    set_instance_parameter_value ddr3_m4 {NUM_OCT_SHARING_INTERFACES} {1}

    add_instance pcie_hip_avmm altera_pcie_sv_hip_avmm 16.0
    set_instance_parameter_value pcie_hip_avmm {pcie_qsys} {1}
    set_instance_parameter_value pcie_hip_avmm {lane_mask_hwtcl} {x4}
    set_instance_parameter_value pcie_hip_avmm {gen123_lane_rate_mode_hwtcl} {Gen3 (8.0 Gbps)}
    set_instance_parameter_value pcie_hip_avmm {port_type_hwtcl} {Native endpoint}
    set_instance_parameter_value pcie_hip_avmm {rxbuffer_rxreq_hwtcl} {Low}
    set_instance_parameter_value pcie_hip_avmm {pll_refclk_freq_hwtcl} {100 MHz}
    set_instance_parameter_value pcie_hip_avmm {set_pld_clk_x1_625MHz_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {in_cvp_mode_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {enable_tl_only_sim_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {use_atx_pll_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {enable_power_on_rst_pulse_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {enable_pcisigtest_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {hip_tag_checking_hwtcl} {1}
    set_instance_parameter_value pcie_hip_avmm {NUM_PREFETCH_MASTERS} {1}
    set_instance_parameter_value pcie_hip_avmm {bar0_type_hwtcl} {1}
    set_instance_parameter_value pcie_hip_avmm {bar1_type_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {bar2_type_hwtcl} {1}
    set_instance_parameter_value pcie_hip_avmm {bar3_type_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {bar4_type_hwtcl} {1}
    set_instance_parameter_value pcie_hip_avmm {bar5_type_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_AVALON_ADDR_B0} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_AVALON_ADDR_B1} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_AVALON_ADDR_B2} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_AVALON_ADDR_B3} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_AVALON_ADDR_B4} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_AVALON_ADDR_B5} {0}
    set_instance_parameter_value pcie_hip_avmm {fixed_address_mode} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_FIXED_AVALON_ADDR_B0} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_FIXED_AVALON_ADDR_B1} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_FIXED_AVALON_ADDR_B2} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_FIXED_AVALON_ADDR_B3} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_FIXED_AVALON_ADDR_B4} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_P2A_FIXED_AVALON_ADDR_B5} {0}
    set_instance_parameter_value pcie_hip_avmm {vendor_id_hwtcl} {6487}
    set_instance_parameter_value pcie_hip_avmm {device_id_hwtcl} {2387}
    set_instance_parameter_value pcie_hip_avmm {revision_id_hwtcl} {179}
    set_instance_parameter_value pcie_hip_avmm {class_code_hwtcl} {67584}
    set_instance_parameter_value pcie_hip_avmm {subsystem_vendor_id_hwtcl} {4277}
    set_instance_parameter_value pcie_hip_avmm {subsystem_device_id_hwtcl} {36948}
    set_instance_parameter_value pcie_hip_avmm {max_payload_size_hwtcl} {256}
    set_instance_parameter_value pcie_hip_avmm {extend_tag_field_hwtcl} {32}
    set_instance_parameter_value pcie_hip_avmm {completion_timeout_hwtcl} {ABCD}
    set_instance_parameter_value pcie_hip_avmm {enable_completion_timeout_disable_hwtcl} {1}
    set_instance_parameter_value pcie_hip_avmm {use_aer_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {ecrc_check_capable_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {ecrc_gen_capable_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {use_crc_forwarding_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {port_link_number_hwtcl} {1}
    set_instance_parameter_value pcie_hip_avmm {dll_active_report_support_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {surprise_down_error_support_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {slotclkcfg_hwtcl} {1}
    set_instance_parameter_value pcie_hip_avmm {msi_multi_message_capable_hwtcl} {4}
    set_instance_parameter_value pcie_hip_avmm {msi_64bit_addressing_capable_hwtcl} {true}
    set_instance_parameter_value pcie_hip_avmm {msi_masking_capable_hwtcl} {false}
    set_instance_parameter_value pcie_hip_avmm {msi_support_hwtcl} {true}
    set_instance_parameter_value pcie_hip_avmm {enable_function_msix_support_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {msix_table_size_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {msix_table_offset_hwtcl} {0.0}
    set_instance_parameter_value pcie_hip_avmm {msix_table_bir_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {msix_pba_offset_hwtcl} {0.0}
    set_instance_parameter_value pcie_hip_avmm {msix_pba_bir_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {enable_slot_register_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {slot_power_scale_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {slot_power_limit_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {slot_number_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {endpoint_l0_latency_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {endpoint_l1_latency_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {vsec_id_hwtcl} {4466}
    set_instance_parameter_value pcie_hip_avmm {vsec_rev_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {user_id_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {CG_COMMON_CLOCK_MODE} {1}
    set_instance_parameter_value pcie_hip_avmm {avmm_width_hwtcl} {128}
    set_instance_parameter_value pcie_hip_avmm {AVALON_ADDR_WIDTH} {64}
    set_instance_parameter_value pcie_hip_avmm {CB_PCIE_MODE} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_PCIE_RX_LITE} {0}
    set_instance_parameter_value pcie_hip_avmm {AST_LITE} {0}
    set_instance_parameter_value pcie_hip_avmm {CG_RXM_IRQ_NUM} {16}
    set_instance_parameter_value pcie_hip_avmm {bypass_tl} {false}
    set_instance_parameter_value pcie_hip_avmm {CG_IMPL_CRA_AV_SLAVE_PORT} {1}
    set_instance_parameter_value pcie_hip_avmm {CG_ENABLE_ADVANCED_INTERRUPT} {1}
    set_instance_parameter_value pcie_hip_avmm {CG_ENABLE_A2P_INTERRUPT} {1}
    set_instance_parameter_value pcie_hip_avmm {CG_ENABLE_HIP_STATUS} {1}
    set_instance_parameter_value pcie_hip_avmm {CG_ENABLE_HIP_STATUS_EXTENSION} {0}
    set_instance_parameter_value pcie_hip_avmm {TX_S_ADDR_WIDTH} {64}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_IS_FIXED} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_NUM_ENTRIES} {2}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_PASS_THRU_BITS} {20}
    set_instance_parameter_value pcie_hip_avmm {BYPASSS_A2P_TRANSLATION} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_RP_S_ADDR_WIDTH} {32}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_0_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_0_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_1_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_1_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_2_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_2_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_3_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_3_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_4_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_4_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_5_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_5_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_6_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_6_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_7_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_7_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_8_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_8_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_9_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_9_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_10_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_10_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_11_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_11_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_12_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_12_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_13_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_13_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_14_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_14_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_15_HIGH} {0}
    set_instance_parameter_value pcie_hip_avmm {CB_A2P_ADDR_MAP_FIXED_TABLE_15_LOW} {0}
    set_instance_parameter_value pcie_hip_avmm {AddressPage} {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}
    set_instance_parameter_value pcie_hip_avmm {PCIeAddress63_32} {0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000}
    set_instance_parameter_value pcie_hip_avmm {PCIeAddress31_0} {0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000,0x00000000}
    set_instance_parameter_value pcie_hip_avmm {RXM_DATA_WIDTH} {64}
    set_instance_parameter_value pcie_hip_avmm {RXM_BEN_WIDTH} {8}
    set_instance_parameter_value pcie_hip_avmm {use_rx_st_be_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {use_ast_parity} {0}
    set_instance_parameter_value pcie_hip_avmm {hip_reconfig_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {expansion_base_address_register_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {io_window_addr_width_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {prefetchable_mem_window_addr_width_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_parameter_override} {0}
    set_instance_parameter_value pcie_hip_avmm {override_tbpartner_driver_setting_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {override_rxbuffer_cred_preset} {0}
    set_instance_parameter_value pcie_hip_avmm {gen3_rxfreqlock_counter_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {force_hrc} {0}
    set_instance_parameter_value pcie_hip_avmm {force_src} {0}
    set_instance_parameter_value pcie_hip_avmm {serial_sim_hwtcl} {1}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_bypass_cdc} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_enable_rx_buffer_checking} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_disable_link_x2_support} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_wrong_device_id} {disable}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_data_pack_rx} {disable}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_ltssm_1ms_timeout} {disable}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_ltssm_freqlocked_check} {disable}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_deskew_comma} {com_deskw}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_device_number} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_pipex1_debug_sel} {disable}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_pclk_out_sel} {pclk}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_no_soft_reset} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_maximum_current} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_d1_support} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_d2_support} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_d0_pme} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_d1_pme} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_d2_pme} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_d3_hot_pme} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_d3_cold_pme} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_low_priority_vc} {single_vc}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_disable_snoop_packet} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_enable_l1_aspm} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_set_l0s} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_l1_exit_latency_sameclock} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_l1_exit_latency_diffclock} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_hot_plug_support} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_extended_tag_reset} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_no_command_completed} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_interrupt_pin} {inta}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_bridge_port_vga_enable} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_bridge_port_ssid_support} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_ssvid} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_ssid} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_eie_before_nfts_count} {4}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_gen2_diffclock_nfts_count} {255}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_gen2_sameclock_nfts_count} {255}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_l0_exit_latency_sameclock} {6}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_l0_exit_latency_diffclock} {6}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_atomic_op_routing} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_atomic_op_completer_32bit} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_atomic_op_completer_64bit} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_cas_completer_128bit} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_ltr_mechanism} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_tph_completer} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_extended_format_field} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_atomic_malformed} {true}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_flr_capability} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_enable_adapter_half_rate_mode} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_vc0_clk_enable} {true}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_register_pipe_signals} {false}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_skp_os_gen3_count} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_tx_cdc_almost_empty} {5}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_rx_l0s_count_idl} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_cdc_dummy_insert_limit} {11}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_ei_delay_powerdown_count} {10}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_skp_os_schedule_count} {0}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_fc_init_timer} {1024}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_l01_entry_latency} {31}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_flow_control_update_count} {30}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_flow_control_timeout_count} {200}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_retry_buffer_last_active_address} {2047}
    set_instance_parameter_value pcie_hip_avmm {advanced_default_hwtcl_reserved_debug} {0}
    set_instance_parameter_value pcie_hip_avmm {use_cvp_update_core_pof_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {pcie_inspector_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {tlp_inspector_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {tlp_inspector_use_signal_probe_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {tlp_insp_trg_dw0_hwtcl} {2049}
    set_instance_parameter_value pcie_hip_avmm {tlp_insp_trg_dw1_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {tlp_insp_trg_dw2_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {tlp_insp_trg_dw3_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {hwtcl_override_g2_txvod} {1}
    set_instance_parameter_value pcie_hip_avmm {rpre_emph_a_val_hwtcl} {9}
    set_instance_parameter_value pcie_hip_avmm {rpre_emph_b_val_hwtcl} {0}
    set_instance_parameter_value pcie_hip_avmm {rpre_emph_c_val_hwtcl} {16}
    set_instance_parameter_value pcie_hip_avmm {rpre_emph_d_val_hwtcl} {13}
    set_instance_parameter_value pcie_hip_avmm {rpre_emph_e_val_hwtcl} {5}
    set_instance_parameter_value pcie_hip_avmm {rvod_sel_a_val_hwtcl} {42}
    set_instance_parameter_value pcie_hip_avmm {rvod_sel_b_val_hwtcl} {38}
    set_instance_parameter_value pcie_hip_avmm {rvod_sel_c_val_hwtcl} {38}
    set_instance_parameter_value pcie_hip_avmm {rvod_sel_d_val_hwtcl} {43}
    set_instance_parameter_value pcie_hip_avmm {rvod_sel_e_val_hwtcl} {15}

    add_instance pcie_reconfig_driver_0 altera_pcie_reconfig_driver 16.0
    set_instance_parameter_value pcie_reconfig_driver_0 {gen123_lane_rate_mode_hwtcl} {Gen3 (8.0 Gbps)}
    set_instance_parameter_value pcie_reconfig_driver_0 {number_of_reconfig_interfaces} {6}
    set_instance_parameter_value pcie_reconfig_driver_0 {enable_cal_busy_hwtcl} {0}

    # connections and connection parameters
    add_connection pcie_hip_avmm.Rxm_BAR0 ddr3_m2.csr avalon
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR0/ddr3_m2.csr arbitrationPriority {1}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR0/ddr3_m2.csr baseAddress {0x0000}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR0/ddr3_m2.csr defaultConnection {0}

    add_connection pcie_hip_avmm.Rxm_BAR0 ddr3_m4.csr avalon
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR0/ddr3_m4.csr arbitrationPriority {1}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR0/ddr3_m4.csr baseAddress {0x00040000}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR0/ddr3_m4.csr defaultConnection {0}

    add_connection pcie_hip_avmm.Rxm_BAR2 ddr3_m4.avl avalon
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR2/ddr3_m4.avl arbitrationPriority {1}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR2/ddr3_m4.avl baseAddress {0x0000000200000000}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR2/ddr3_m4.avl defaultConnection {0}

    add_connection pcie_hip_avmm.Rxm_BAR2 ddr3_m2.avl avalon
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR2/ddr3_m2.avl arbitrationPriority {1}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR2/ddr3_m2.avl baseAddress {0x0000}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR2/ddr3_m2.avl defaultConnection {0}

    add_connection pcie_hip_avmm.Rxm_BAR4 pcie_hip_avmm.Cra avalon
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR4/pcie_hip_avmm.Cra arbitrationPriority {1}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR4/pcie_hip_avmm.Cra baseAddress {0x4000}
    set_connection_parameter_value pcie_hip_avmm.Rxm_BAR4/pcie_hip_avmm.Cra defaultConnection {0}

    add_connection pcie_reconfig_driver_0.reconfig_mgmt alt_xcvr_reconfig_0.reconfig_mgmt avalon
    set_connection_parameter_value pcie_reconfig_driver_0.reconfig_mgmt/alt_xcvr_reconfig_0.reconfig_mgmt arbitrationPriority {1}
    set_connection_parameter_value pcie_reconfig_driver_0.reconfig_mgmt/alt_xcvr_reconfig_0.reconfig_mgmt baseAddress {0x0000}
    set_connection_parameter_value pcie_reconfig_driver_0.reconfig_mgmt/alt_xcvr_reconfig_0.reconfig_mgmt defaultConnection {0}

    add_connection clk_0.clk ddr3_m2.pll_ref_clk clock

    add_connection clk_1.clk ddr3_m4.pll_ref_clk clock

    add_connection pcie_hip_avmm.coreclkout pcie_reconfig_driver_0.pld_clk clock

    add_connection pcie_reconfig_driver_0.hip_currentspeed pcie_hip_avmm.hip_currentspeed conduit
    set_connection_parameter_value pcie_reconfig_driver_0.hip_currentspeed/pcie_hip_avmm.hip_currentspeed endPort {}
    set_connection_parameter_value pcie_reconfig_driver_0.hip_currentspeed/pcie_hip_avmm.hip_currentspeed endPortLSB {0}
    set_connection_parameter_value pcie_reconfig_driver_0.hip_currentspeed/pcie_hip_avmm.hip_currentspeed startPort {}
    set_connection_parameter_value pcie_reconfig_driver_0.hip_currentspeed/pcie_hip_avmm.hip_currentspeed startPortLSB {0}
    set_connection_parameter_value pcie_reconfig_driver_0.hip_currentspeed/pcie_hip_avmm.hip_currentspeed width {0}

    add_connection pcie_reconfig_driver_0.hip_status_drv pcie_hip_avmm.hip_status conduit
    set_connection_parameter_value pcie_reconfig_driver_0.hip_status_drv/pcie_hip_avmm.hip_status endPort {}
    set_connection_parameter_value pcie_reconfig_driver_0.hip_status_drv/pcie_hip_avmm.hip_status endPortLSB {0}
    set_connection_parameter_value pcie_reconfig_driver_0.hip_status_drv/pcie_hip_avmm.hip_status startPort {}
    set_connection_parameter_value pcie_reconfig_driver_0.hip_status_drv/pcie_hip_avmm.hip_status startPortLSB {0}
    set_connection_parameter_value pcie_reconfig_driver_0.hip_status_drv/pcie_hip_avmm.hip_status width {0}

    add_connection alt_xcvr_reconfig_0.reconfig_busy pcie_reconfig_driver_0.reconfig_busy conduit
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_busy/pcie_reconfig_driver_0.reconfig_busy endPort {}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_busy/pcie_reconfig_driver_0.reconfig_busy endPortLSB {0}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_busy/pcie_reconfig_driver_0.reconfig_busy startPort {}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_busy/pcie_reconfig_driver_0.reconfig_busy startPortLSB {0}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_busy/pcie_reconfig_driver_0.reconfig_busy width {0}

    add_connection alt_xcvr_reconfig_0.reconfig_from_xcvr pcie_hip_avmm.reconfig_from_xcvr conduit
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_from_xcvr/pcie_hip_avmm.reconfig_from_xcvr endPort {}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_from_xcvr/pcie_hip_avmm.reconfig_from_xcvr endPortLSB {0}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_from_xcvr/pcie_hip_avmm.reconfig_from_xcvr startPort {}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_from_xcvr/pcie_hip_avmm.reconfig_from_xcvr startPortLSB {0}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_from_xcvr/pcie_hip_avmm.reconfig_from_xcvr width {0}

    add_connection alt_xcvr_reconfig_0.reconfig_to_xcvr pcie_hip_avmm.reconfig_to_xcvr conduit
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_to_xcvr/pcie_hip_avmm.reconfig_to_xcvr endPort {}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_to_xcvr/pcie_hip_avmm.reconfig_to_xcvr endPortLSB {0}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_to_xcvr/pcie_hip_avmm.reconfig_to_xcvr startPort {}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_to_xcvr/pcie_hip_avmm.reconfig_to_xcvr startPortLSB {0}
    set_connection_parameter_value alt_xcvr_reconfig_0.reconfig_to_xcvr/pcie_hip_avmm.reconfig_to_xcvr width {0}

    add_connection clk_1.clk_reset ddr3_m4.global_reset reset

    add_connection clk_0.clk_reset ddr3_m2.global_reset reset

    add_connection clk_1.clk_reset ddr3_m4.soft_reset reset

    add_connection clk_0.clk_reset ddr3_m2.soft_reset reset

    # exported interfaces
    add_interface clk clock sink
    set_interface_property clk EXPORT_OF clk_0.clk_in
    add_interface clk_1 clock sink
    set_interface_property clk_1 EXPORT_OF clk_1.clk_in
    add_interface hip_ctrl conduit end
    set_interface_property hip_ctrl EXPORT_OF pcie_hip_avmm.hip_ctrl
    add_interface hip_serial conduit end
    set_interface_property hip_serial EXPORT_OF pcie_hip_avmm.hip_serial
    add_interface memory conduit end
    set_interface_property memory EXPORT_OF ddr3_m2.memory
    add_interface memory_1 conduit end
    set_interface_property memory_1 EXPORT_OF ddr3_m4.memory
    add_interface mgmt_clk clock sink
    set_interface_property mgmt_clk EXPORT_OF alt_xcvr_reconfig_0.mgmt_clk_clk
    add_interface mgmt_rst reset sink
    set_interface_property mgmt_rst EXPORT_OF alt_xcvr_reconfig_0.mgmt_rst_reset
    add_interface oct conduit end
    set_interface_property oct EXPORT_OF ddr3_m2.oct
    add_interface oct_1 conduit end
    set_interface_property oct_1 EXPORT_OF ddr3_m4.oct
    add_interface pcie_npor conduit end
    set_interface_property pcie_npor EXPORT_OF pcie_hip_avmm.npor
    add_interface pcie_refclock clock sink
    set_interface_property pcie_refclock EXPORT_OF pcie_hip_avmm.refclk
    add_interface reconfig_xcvr_clk clock sink
    set_interface_property reconfig_xcvr_clk EXPORT_OF pcie_reconfig_driver_0.reconfig_xcvr_clk
    add_interface reconfig_xcvr_rst reset sink
    set_interface_property reconfig_xcvr_rst EXPORT_OF pcie_reconfig_driver_0.reconfig_xcvr_rst
    add_interface reset reset sink
    set_interface_property reset EXPORT_OF clk_0.clk_in_reset
    add_interface reset_1 reset sink
    set_interface_property reset_1 EXPORT_OF clk_1.clk_in_reset

    # interconnect requirements
    set_interconnect_requirement {$system} {qsys_mm.clockCrossingAdapter} {HANDSHAKE}
    set_interconnect_requirement {$system} {qsys_mm.maxAdditionalLatency} {1}
    set_interconnect_requirement {$system} {qsys_mm.enableEccProtection} {FALSE}
    set_interconnect_requirement {$system} {qsys_mm.insertDefaultSlave} {FALSE}
}
